
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace HiiP.Framework.Security.UserManagement
{
    partial class DelegationDetail
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private HiiP.Framework.Security.UserManagement.DelegationDetailPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            this.ultraGroupBox2 = new Infragistics.Win.Misc.UltraGroupBox();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.ultraComboUnit = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.ultraComboBranch = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.ultraComboSubUnit = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.ultraLabel1 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel2 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel3 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraGroupBox3 = new Infragistics.Win.Misc.UltraGroupBox();
            this.tableLayoutPanel6 = new System.Windows.Forms.TableLayoutPanel();
            this.ultraComboGrade = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.ultraLabel6 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraComboAct = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.ultraLabel8 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel7 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel10 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel11 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel12 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel13 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraDateTimeEditorStartDate = new Infragistics.Win.UltraWinEditors.UltraDateTimeEditor();
            this.ultraDateTimeEditorEndDate = new Infragistics.Win.UltraWinEditors.UltraDateTimeEditor();
            this.ultraGroupBox1 = new Infragistics.Win.Misc.UltraGroupBox();
            this.tableLayoutPanel4 = new System.Windows.Forms.TableLayoutPanel();
            this.ddlDelegationFunction = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.ultraLabel4 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel9 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel5 = new Infragistics.Win.Misc.UltraLabel();
            this.lblDelegationValueID = new Infragistics.Win.Misc.UltraLabel();
            this.btnSave = new Infragistics.Win.Misc.UltraButton();
            this.btnCancel = new Infragistics.Win.Misc.UltraButton();
            this.tableLayoutPanel5 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.ultraComboEditor1 = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.ultraComboEditor2 = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.ultraComboEditor3 = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.errorProvider = new System.Windows.Forms.ErrorProvider(this.components);
            this.flowLayoutPanel2 = new System.Windows.Forms.FlowLayoutPanel();
            this.txtValue = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.txtOperationConditions = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.txtPolicyValue = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.txtReferenceNo = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox2)).BeginInit();
            this.ultraGroupBox2.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboUnit)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboBranch)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboSubUnit)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox3)).BeginInit();
            this.ultraGroupBox3.SuspendLayout();
            this.tableLayoutPanel6.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboGrade)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboAct)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDateTimeEditorStartDate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDateTimeEditorEndDate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox1)).BeginInit();
            this.ultraGroupBox1.SuspendLayout();
            this.tableLayoutPanel4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ddlDelegationFunction)).BeginInit();
            this.tableLayoutPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditor1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditor2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditor3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider)).BeginInit();
            this.flowLayoutPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.txtValue)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtOperationConditions)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtPolicyValue)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtReferenceNo)).BeginInit();
            this.SuspendLayout();
            // 
            // ultraGroupBox2
            // 
            this.ultraGroupBox2.Controls.Add(this.tableLayoutPanel3);
            this.ultraGroupBox2.Dock = System.Windows.Forms.DockStyle.Top;
            this.ultraGroupBox2.Location = new System.Drawing.Point(0, 116);
            this.ultraGroupBox2.Name = "ultraGroupBox2";
            this.ultraGroupBox2.Size = new System.Drawing.Size(978, 97);
            this.ultraGroupBox2.TabIndex = 4;
            this.ultraGroupBox2.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel3.ColumnCount = 2;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel3.Controls.Add(this.ultraComboUnit, 1, 2);
            this.tableLayoutPanel3.Controls.Add(this.ultraComboBranch, 1, 1);
            this.tableLayoutPanel3.Controls.Add(this.ultraComboSubUnit, 1, 3);
            this.tableLayoutPanel3.Controls.Add(this.ultraLabel1, 0, 1);
            this.tableLayoutPanel3.Controls.Add(this.ultraLabel2, 0, 2);
            this.tableLayoutPanel3.Controls.Add(this.ultraLabel3, 0, 3);
            this.tableLayoutPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel3.Location = new System.Drawing.Point(3, 0);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 4;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 8F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(972, 94);
            this.tableLayoutPanel3.TabIndex = 4;
            // 
            // ultraComboUnit
            // 
            this.ultraComboUnit.AlwaysInEditMode = true;
            this.ultraComboUnit.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.ultraComboUnit.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ultraComboUnit.Location = new System.Drawing.Point(62, 39);
            this.ultraComboUnit.Name = "ultraComboUnit";
            this.ultraComboUnit.Size = new System.Drawing.Size(282, 23);
            this.ultraComboUnit.SyncWithCurrencyManager = false;
            this.ultraComboUnit.TabIndex = 4;
            this.ultraComboUnit.ValueChanged += new System.EventHandler(this.ultraComboUnit_ValueChanged);
            // 
            // ultraComboBranch
            // 
            this.ultraComboBranch.AlwaysInEditMode = true;
            this.ultraComboBranch.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.ultraComboBranch.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ultraComboBranch.Location = new System.Drawing.Point(62, 11);
            this.ultraComboBranch.Name = "ultraComboBranch";
            this.ultraComboBranch.Size = new System.Drawing.Size(282, 23);
            this.ultraComboBranch.SyncWithCurrencyManager = false;
            this.ultraComboBranch.TabIndex = 3;
            this.ultraComboBranch.ValueChanged += new System.EventHandler(this.ultraComboBranch_ValueChanged);
            // 
            // ultraComboSubUnit
            // 
            this.ultraComboSubUnit.AlwaysInEditMode = true;
            this.ultraComboSubUnit.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.ultraComboSubUnit.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ultraComboSubUnit.Location = new System.Drawing.Point(62, 67);
            this.ultraComboSubUnit.Name = "ultraComboSubUnit";
            this.ultraComboSubUnit.Size = new System.Drawing.Size(282, 23);
            this.ultraComboSubUnit.SyncWithCurrencyManager = false;
            this.ultraComboSubUnit.TabIndex = 5;
            // 
            // ultraLabel1
            // 
            this.ultraLabel1.Anchor = System.Windows.Forms.AnchorStyles.Right;
            appearance14.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance14.TextHAlignAsString = "Right";
            this.ultraLabel1.Appearance = appearance14;
            this.ultraLabel1.AutoSize = true;
            this.ultraLabel1.Location = new System.Drawing.Point(3, 14);
            this.ultraLabel1.Name = "ultraLabel1";
            this.ultraLabel1.Size = new System.Drawing.Size(53, 16);
            this.ultraLabel1.TabIndex = 9;
            this.ultraLabel1.Text = "* Branch";
            // 
            // ultraLabel2
            // 
            this.ultraLabel2.Anchor = System.Windows.Forms.AnchorStyles.Right;
            appearance15.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance15.TextHAlignAsString = "Right";
            this.ultraLabel2.Appearance = appearance15;
            this.ultraLabel2.AutoSize = true;
            this.ultraLabel2.Location = new System.Drawing.Point(30, 42);
            this.ultraLabel2.Name = "ultraLabel2";
            this.ultraLabel2.Size = new System.Drawing.Size(26, 16);
            this.ultraLabel2.TabIndex = 10;
            this.ultraLabel2.Text = "Unit";
            // 
            // ultraLabel3
            // 
            this.ultraLabel3.Anchor = System.Windows.Forms.AnchorStyles.Right;
            appearance16.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance16.TextHAlignAsString = "Right";
            this.ultraLabel3.Appearance = appearance16;
            this.ultraLabel3.AutoSize = true;
            this.ultraLabel3.Location = new System.Drawing.Point(10, 71);
            this.ultraLabel3.Name = "ultraLabel3";
            this.ultraLabel3.Size = new System.Drawing.Size(46, 16);
            this.ultraLabel3.TabIndex = 11;
            this.ultraLabel3.Text = "Subunit";
            // 
            // ultraGroupBox3
            // 
            this.ultraGroupBox3.Controls.Add(this.tableLayoutPanel6);
            this.ultraGroupBox3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox3.Location = new System.Drawing.Point(0, 213);
            this.ultraGroupBox3.Name = "ultraGroupBox3";
            this.ultraGroupBox3.Size = new System.Drawing.Size(978, 274);
            this.ultraGroupBox3.TabIndex = 6;
            this.ultraGroupBox3.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
            // 
            // tableLayoutPanel6
            // 
            this.tableLayoutPanel6.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel6.ColumnCount = 2;
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel6.Controls.Add(this.ultraComboGrade, 1, 1);
            this.tableLayoutPanel6.Controls.Add(this.ultraLabel6, 0, 1);
            this.tableLayoutPanel6.Controls.Add(this.ultraLabel12, 0, 6);
            this.tableLayoutPanel6.Controls.Add(this.ultraLabel13, 0, 7);
            this.tableLayoutPanel6.Controls.Add(this.ultraDateTimeEditorStartDate, 1, 6);
            this.tableLayoutPanel6.Controls.Add(this.ultraDateTimeEditorEndDate, 1, 7);
            this.tableLayoutPanel6.Controls.Add(this.ultraLabel11, 0, 5);
            this.tableLayoutPanel6.Controls.Add(this.txtOperationConditions, 1, 5);
            this.tableLayoutPanel6.Controls.Add(this.ultraLabel10, 0, 4);
            this.tableLayoutPanel6.Controls.Add(this.txtPolicyValue, 1, 4);
            this.tableLayoutPanel6.Controls.Add(this.ultraLabel7, 0, 3);
            this.tableLayoutPanel6.Controls.Add(this.ultraLabel8, 0, 2);
            this.tableLayoutPanel6.Controls.Add(this.txtValue, 1, 3);
            this.tableLayoutPanel6.Controls.Add(this.ultraComboAct, 1, 2);
            this.tableLayoutPanel6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel6.Location = new System.Drawing.Point(3, 0);
            this.tableLayoutPanel6.Name = "tableLayoutPanel6";
            this.tableLayoutPanel6.RowCount = 8;
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 8F));
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.tableLayoutPanel6.Size = new System.Drawing.Size(972, 271);
            this.tableLayoutPanel6.TabIndex = 5;
            // 
            // ultraComboGrade
            // 
            this.ultraComboGrade.AlwaysInEditMode = true;
            this.ultraComboGrade.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.ultraComboGrade.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ultraComboGrade.Location = new System.Drawing.Point(135, 11);
            this.ultraComboGrade.Name = "ultraComboGrade";
            this.ultraComboGrade.Size = new System.Drawing.Size(282, 23);
            this.ultraComboGrade.SyncWithCurrencyManager = false;
            this.ultraComboGrade.TabIndex = 3;
            // 
            // ultraLabel6
            // 
            this.ultraLabel6.Anchor = System.Windows.Forms.AnchorStyles.Right;
            appearance5.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance5.TextHAlignAsString = "Right";
            this.ultraLabel6.Appearance = appearance5;
            this.ultraLabel6.AutoSize = true;
            this.ultraLabel6.Location = new System.Drawing.Point(81, 14);
            this.ultraLabel6.Name = "ultraLabel6";
            this.ultraLabel6.Size = new System.Drawing.Size(48, 16);
            this.ultraLabel6.TabIndex = 9;
            this.ultraLabel6.Text = "* Grade";
            // 
            // ultraComboAct
            // 
            this.ultraComboAct.AlwaysInEditMode = true;
            this.ultraComboAct.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.ultraComboAct.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ultraComboAct.Location = new System.Drawing.Point(135, 39);
            this.ultraComboAct.Name = "ultraComboAct";
            this.ultraComboAct.Size = new System.Drawing.Size(282, 23);
            this.ultraComboAct.SyncWithCurrencyManager = false;
            this.ultraComboAct.TabIndex = 5;
            // 
            // ultraLabel8
            // 
            this.ultraLabel8.Anchor = System.Windows.Forms.AnchorStyles.Right;
            appearance1.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance1.TextHAlignAsString = "Right";
            this.ultraLabel8.Appearance = appearance1;
            this.ultraLabel8.AutoSize = true;
            this.ultraLabel8.Location = new System.Drawing.Point(97, 42);
            this.ultraLabel8.Name = "ultraLabel8";
            this.ultraLabel8.Size = new System.Drawing.Size(32, 16);
            this.ultraLabel8.TabIndex = 11;
            this.ultraLabel8.Text = "* Act";
            // 
            // ultraLabel7
            // 
            this.ultraLabel7.Anchor = System.Windows.Forms.AnchorStyles.Right;
            appearance6.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance6.TextHAlignAsString = "Right";
            this.ultraLabel7.Appearance = appearance6;
            this.ultraLabel7.AutoSize = true;
            this.ultraLabel7.Location = new System.Drawing.Point(94, 70);
            this.ultraLabel7.Name = "ultraLabel7";
            this.ultraLabel7.Size = new System.Drawing.Size(35, 16);
            this.ultraLabel7.TabIndex = 10;
            this.ultraLabel7.Text = "Value";
            // 
            // ultraLabel10
            // 
            this.ultraLabel10.Anchor = System.Windows.Forms.AnchorStyles.Right;
            appearance11.TextHAlignAsString = "Right";
            this.ultraLabel10.Appearance = appearance11;
            this.ultraLabel10.AutoSize = true;
            this.ultraLabel10.Location = new System.Drawing.Point(61, 98);
            this.ultraLabel10.Name = "ultraLabel10";
            this.ultraLabel10.Size = new System.Drawing.Size(68, 16);
            this.ultraLabel10.TabIndex = 12;
            this.ultraLabel10.Text = "Policy value";
            // 
            // ultraLabel11
            // 
            this.ultraLabel11.Anchor = System.Windows.Forms.AnchorStyles.Right;
            appearance12.TextHAlignAsString = "Right";
            this.ultraLabel11.Appearance = appearance12;
            this.ultraLabel11.AutoSize = true;
            this.ultraLabel11.Location = new System.Drawing.Point(3, 159);
            this.ultraLabel11.Name = "ultraLabel11";
            this.ultraLabel11.Size = new System.Drawing.Size(126, 16);
            this.ultraLabel11.TabIndex = 13;
            this.ultraLabel11.Text = "Operational conditions";
            // 
            // ultraLabel12
            // 
            this.ultraLabel12.Anchor = System.Windows.Forms.AnchorStyles.Right;
            appearance2.TextHAlignAsString = "Right";
            this.ultraLabel12.Appearance = appearance2;
            this.ultraLabel12.AutoSize = true;
            this.ultraLabel12.Location = new System.Drawing.Point(64, 221);
            this.ultraLabel12.Name = "ultraLabel12";
            this.ultraLabel12.Size = new System.Drawing.Size(65, 16);
            this.ultraLabel12.TabIndex = 15;
            this.ultraLabel12.Text = "*Start date";
            // 
            // ultraLabel13
            // 
            this.ultraLabel13.Anchor = System.Windows.Forms.AnchorStyles.Right;
            appearance13.TextHAlignAsString = "Right";
            this.ultraLabel13.Appearance = appearance13;
            this.ultraLabel13.AutoSize = true;
            this.ultraLabel13.Location = new System.Drawing.Point(69, 249);
            this.ultraLabel13.Name = "ultraLabel13";
            this.ultraLabel13.Size = new System.Drawing.Size(60, 16);
            this.ultraLabel13.TabIndex = 16;
            this.ultraLabel13.Text = "*End date";
            // 
            // ultraDateTimeEditorStartDate
            // 
            this.ultraDateTimeEditorStartDate.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.ultraDateTimeEditorStartDate.DateTime = new System.DateTime(2010, 1, 8, 0, 0, 0, 0);
            this.ultraDateTimeEditorStartDate.Location = new System.Drawing.Point(135, 218);
            this.ultraDateTimeEditorStartDate.MaskInput = "{date} {time}";
            this.ultraDateTimeEditorStartDate.Name = "ultraDateTimeEditorStartDate";
            this.ultraDateTimeEditorStartDate.Nullable = false;
            this.ultraDateTimeEditorStartDate.Size = new System.Drawing.Size(164, 23);
            this.ultraDateTimeEditorStartDate.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.ultraDateTimeEditorStartDate.TabIndex = 19;
            this.ultraDateTimeEditorStartDate.Value = new System.DateTime(2010, 1, 8, 0, 0, 0, 0);
            // 
            // ultraDateTimeEditorEndDate
            // 
            this.ultraDateTimeEditorEndDate.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.ultraDateTimeEditorEndDate.DateTime = new System.DateTime(2010, 1, 8, 0, 0, 0, 0);
            this.ultraDateTimeEditorEndDate.Location = new System.Drawing.Point(135, 246);
            this.ultraDateTimeEditorEndDate.MaskInput = "{date} {time}";
            this.ultraDateTimeEditorEndDate.Name = "ultraDateTimeEditorEndDate";
            this.ultraDateTimeEditorEndDate.Nullable = false;
            this.ultraDateTimeEditorEndDate.Size = new System.Drawing.Size(164, 23);
            this.ultraDateTimeEditorEndDate.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.ultraDateTimeEditorEndDate.TabIndex = 20;
            this.ultraDateTimeEditorEndDate.Value = new System.DateTime(2010, 1, 8, 0, 0, 0, 0);
            // 
            // ultraGroupBox1
            // 
            this.ultraGroupBox1.Controls.Add(this.tableLayoutPanel4);
            this.ultraGroupBox1.Dock = System.Windows.Forms.DockStyle.Top;
            this.ultraGroupBox1.Location = new System.Drawing.Point(0, 0);
            this.ultraGroupBox1.Name = "ultraGroupBox1";
            this.ultraGroupBox1.Size = new System.Drawing.Size(978, 116);
            this.ultraGroupBox1.TabIndex = 3;
            this.ultraGroupBox1.Text = "Delegation details";
            this.ultraGroupBox1.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
            // 
            // tableLayoutPanel4
            // 
            this.tableLayoutPanel4.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel4.ColumnCount = 2;
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel4.Controls.Add(this.ddlDelegationFunction, 1, 3);
            this.tableLayoutPanel4.Controls.Add(this.ultraLabel4, 0, 3);
            this.tableLayoutPanel4.Controls.Add(this.ultraLabel9, 0, 2);
            this.tableLayoutPanel4.Controls.Add(this.ultraLabel5, 0, 1);
            this.tableLayoutPanel4.Controls.Add(this.lblDelegationValueID, 1, 1);
            this.tableLayoutPanel4.Controls.Add(this.txtReferenceNo, 1, 2);
            this.tableLayoutPanel4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel4.Location = new System.Drawing.Point(3, 18);
            this.tableLayoutPanel4.Name = "tableLayoutPanel4";
            this.tableLayoutPanel4.RowCount = 4;
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 8F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.tableLayoutPanel4.Size = new System.Drawing.Size(972, 95);
            this.tableLayoutPanel4.TabIndex = 3;
            // 
            // ddlDelegationFunction
            // 
            this.ddlDelegationFunction.AlwaysInEditMode = true;
            this.ddlDelegationFunction.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.ddlDelegationFunction.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ddlDelegationFunction.Location = new System.Drawing.Point(130, 68);
            this.ddlDelegationFunction.Name = "ddlDelegationFunction";
            this.ddlDelegationFunction.Size = new System.Drawing.Size(282, 23);
            this.ddlDelegationFunction.SyncWithCurrencyManager = false;
            this.ddlDelegationFunction.TabIndex = 3;
            // 
            // ultraLabel4
            // 
            this.ultraLabel4.Anchor = System.Windows.Forms.AnchorStyles.Right;
            appearance3.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance3.TextHAlignAsString = "Right";
            this.ultraLabel4.Appearance = appearance3;
            this.ultraLabel4.AutoSize = true;
            this.ultraLabel4.Location = new System.Drawing.Point(3, 71);
            this.ultraLabel4.Name = "ultraLabel4";
            this.ultraLabel4.Size = new System.Drawing.Size(121, 16);
            this.ultraLabel4.TabIndex = 10;
            this.ultraLabel4.Text = "* Delegation function";
            // 
            // ultraLabel9
            // 
            this.ultraLabel9.Anchor = System.Windows.Forms.AnchorStyles.Right;
            appearance8.TextHAlignAsString = "Right";
            this.ultraLabel9.Appearance = appearance8;
            this.ultraLabel9.AutoSize = true;
            this.ultraLabel9.Location = new System.Drawing.Point(44, 42);
            this.ultraLabel9.Name = "ultraLabel9";
            this.ultraLabel9.Size = new System.Drawing.Size(80, 16);
            this.ultraLabel9.TabIndex = 12;
            this.ultraLabel9.Text = "Reference no.";
            // 
            // ultraLabel5
            // 
            this.ultraLabel5.Anchor = System.Windows.Forms.AnchorStyles.Right;
            appearance4.TextHAlignAsString = "Right";
            this.ultraLabel5.Appearance = appearance4;
            this.ultraLabel5.AutoSize = true;
            this.ultraLabel5.Location = new System.Drawing.Point(107, 14);
            this.ultraLabel5.Name = "ultraLabel5";
            this.ultraLabel5.Size = new System.Drawing.Size(17, 16);
            this.ultraLabel5.TabIndex = 11;
            this.ultraLabel5.Text = "ID";
            // 
            // lblDelegationValueID
            // 
            this.lblDelegationValueID.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblDelegationValueID.Location = new System.Drawing.Point(130, 11);
            this.lblDelegationValueID.Name = "lblDelegationValueID";
            this.lblDelegationValueID.Size = new System.Drawing.Size(100, 22);
            this.lblDelegationValueID.TabIndex = 13;
            // 
            // btnSave
            // 
            this.btnSave.Location = new System.Drawing.Point(819, 3);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new System.Drawing.Size(75, 23);
            this.btnSave.TabIndex = 0;
            this.btnSave.Text = "&Save";
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // btnCancel
            // 
            this.btnCancel.Location = new System.Drawing.Point(900, 3);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(75, 23);
            this.btnCancel.TabIndex = 1;
            this.btnCancel.Text = "&Cancel";
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // tableLayoutPanel5
            // 
            this.tableLayoutPanel5.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel5.ColumnCount = 2;
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel5.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel5.Name = "tableLayoutPanel5";
            this.tableLayoutPanel5.RowCount = 2;
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel5.Size = new System.Drawing.Size(200, 100);
            this.tableLayoutPanel5.TabIndex = 0;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel2.ColumnCount = 2;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.Controls.Add(this.ultraComboEditor1, 1, 2);
            this.tableLayoutPanel2.Controls.Add(this.ultraComboEditor2, 1, 1);
            this.tableLayoutPanel2.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 3;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(200, 100);
            this.tableLayoutPanel2.TabIndex = 0;
            // 
            // ultraComboEditor1
            // 
            this.ultraComboEditor1.AlwaysInEditMode = true;
            this.ultraComboEditor1.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ultraComboEditor1.Location = new System.Drawing.Point(3, 43);
            this.ultraComboEditor1.Name = "ultraComboEditor1";
            this.ultraComboEditor1.Size = new System.Drawing.Size(194, 21);
            this.ultraComboEditor1.SyncWithCurrencyManager = false;
            this.ultraComboEditor1.TabIndex = 4;
            // 
            // ultraComboEditor2
            // 
            this.ultraComboEditor2.AlwaysInEditMode = true;
            this.ultraComboEditor2.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ultraComboEditor2.Location = new System.Drawing.Point(3, 23);
            this.ultraComboEditor2.Name = "ultraComboEditor2";
            this.ultraComboEditor2.Size = new System.Drawing.Size(194, 21);
            this.ultraComboEditor2.SyncWithCurrencyManager = false;
            this.ultraComboEditor2.TabIndex = 3;
            // 
            // ultraComboEditor3
            // 
            this.ultraComboEditor3.AlwaysInEditMode = true;
            this.ultraComboEditor3.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ultraComboEditor3.Location = new System.Drawing.Point(138, 77);
            this.ultraComboEditor3.Name = "ultraComboEditor3";
            this.ultraComboEditor3.Size = new System.Drawing.Size(282, 21);
            this.ultraComboEditor3.SyncWithCurrencyManager = false;
            this.ultraComboEditor3.TabIndex = 5;
            // 
            // errorProvider
            // 
            this.errorProvider.BlinkRate = 500;
            this.errorProvider.ContainerControl = this;
            // 
            // flowLayoutPanel2
            // 
            this.flowLayoutPanel2.Controls.Add(this.btnCancel);
            this.flowLayoutPanel2.Controls.Add(this.btnSave);
            this.flowLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.flowLayoutPanel2.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft;
            this.flowLayoutPanel2.Location = new System.Drawing.Point(0, 487);
            this.flowLayoutPanel2.Name = "flowLayoutPanel2";
            this.flowLayoutPanel2.Size = new System.Drawing.Size(978, 26);
            this.flowLayoutPanel2.TabIndex = 9;
            // 
            // txtValue
            // 
            this.txtValue.Location = new System.Drawing.Point(138, 67);
            this.txtValue.MaxLength = 50;
            this.txtValue.Name = "txtValue";
            this.txtValue.Size = new System.Drawing.Size(282, 23);
            this.txtValue.TabIndex = 18;
            // 
            // txtOperationConditions
            // 
            this.txtOperationConditions.AcceptsReturn = true;
            this.txtOperationConditions.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)));
            this.txtOperationConditions.Location = new System.Drawing.Point(138, 123);
            this.txtOperationConditions.MaxLength = 256;
            this.txtOperationConditions.Multiline = true;
            this.txtOperationConditions.Name = "txtOperationConditions";
            this.txtOperationConditions.Size = new System.Drawing.Size(282, 89);
            this.txtOperationConditions.TabIndex = 14;
            // 
            // txtPolicyValue
            // 
            this.txtPolicyValue.Location = new System.Drawing.Point(138, 95);
            this.txtPolicyValue.MaxLength = 50;
            this.txtPolicyValue.Name = "txtPolicyValue";
            this.txtPolicyValue.Size = new System.Drawing.Size(282, 23);
            this.txtPolicyValue.TabIndex = 17;
            // 
            // txtReferenceNo
            // 
            this.txtReferenceNo.Location = new System.Drawing.Point(138, 39);
            this.txtReferenceNo.MaxLength = 256;
            this.txtReferenceNo.Name = "txtReferenceNo";
            this.txtReferenceNo.Size = new System.Drawing.Size(282, 23);
            this.txtReferenceNo.TabIndex = 14;
            // 
            // DelegationDetail
            // 
            this.AcceptButton = this.btnSave;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            this.AutoScrollMinSize = new System.Drawing.Size(750, 480);
            this.CancelButton = this.btnCancel;
            this.CheckDirtyRequired = true;
            this.Controls.Add(this.ultraGroupBox3);
            this.Controls.Add(this.flowLayoutPanel2);
            this.Controls.Add(this.ultraGroupBox2);
            this.Controls.Add(this.ultraGroupBox1);
            this.Key = "NewFinancialDelegation";
            this.Name = "DelegationDetail";
            this.Size = new System.Drawing.Size(978, 513);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox2)).EndInit();
            this.ultraGroupBox2.ResumeLayout(false);
            this.tableLayoutPanel3.ResumeLayout(false);
            this.tableLayoutPanel3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboUnit)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboBranch)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboSubUnit)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox3)).EndInit();
            this.ultraGroupBox3.ResumeLayout(false);
            this.tableLayoutPanel6.ResumeLayout(false);
            this.tableLayoutPanel6.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboGrade)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboAct)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDateTimeEditorStartDate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDateTimeEditorEndDate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox1)).EndInit();
            this.ultraGroupBox1.ResumeLayout(false);
            this.tableLayoutPanel4.ResumeLayout(false);
            this.tableLayoutPanel4.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ddlDelegationFunction)).EndInit();
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditor1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditor2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditor3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider)).EndInit();
            this.flowLayoutPanel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.txtValue)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtOperationConditions)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtPolicyValue)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtReferenceNo)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox2;
        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox3;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel5;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ultraComboUnit;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ultraComboSubUnit;
        private Infragistics.Win.Misc.UltraLabel ultraLabel1;
        private Infragistics.Win.Misc.UltraLabel ultraLabel2;
        private Infragistics.Win.Misc.UltraLabel ultraLabel3;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel6;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ultraComboGrade;
        private Infragistics.Win.Misc.UltraLabel ultraLabel6;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ultraComboAct;
        private Infragistics.Win.Misc.UltraLabel ultraLabel8;
        private Infragistics.Win.Misc.UltraLabel ultraLabel7;
        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel4;
        private Infragistics.Win.Misc.UltraLabel ultraLabel4;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ddlDelegationFunction;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ultraComboBranch;
        private Infragistics.Win.Misc.UltraLabel ultraLabel9;
        private Infragistics.Win.Misc.UltraLabel ultraLabel5;
        private Infragistics.Win.Misc.UltraLabel ultraLabel10;
        private Infragistics.Win.Misc.UltraLabel ultraLabel11;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor txtOperationConditions;
        private Infragistics.Win.Misc.UltraLabel ultraLabel12;
        private Infragistics.Win.Misc.UltraLabel ultraLabel13;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor txtPolicyValue;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor txtValue;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ultraComboEditor1;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ultraComboEditor2;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ultraComboEditor3;
        private Infragistics.Win.Misc.UltraButton btnSave;
        private Infragistics.Win.Misc.UltraButton btnCancel;
        private Infragistics.Win.Misc.UltraLabel lblDelegationValueID;
        private Infragistics.Win.UltraWinEditors.UltraDateTimeEditor ultraDateTimeEditorStartDate;
        private Infragistics.Win.UltraWinEditors.UltraDateTimeEditor ultraDateTimeEditorEndDate;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor txtReferenceNo;
        private System.Windows.Forms.ErrorProvider errorProvider;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel2;
    }
}

