using System.Reflection;
using System.Runtime.InteropServices;
using System.Diagnostics.CodeAnalysis;

[assembly: AssemblyTitle("HiiP.Framework.Security.UserManagement")]
[assembly: AssemblyDescription("HiiP Framework Security UserManagement")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]
[assembly: AssemblyFileVersion("5.2.21222.0")]
// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("bdb5c1ee-832d-4983-a3b4-547e31603385")]


[module: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "HiiP.Framework.Security.UserManagement.IMaintainDelegation")]
[module: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "HiiP.Framework.Security.UserManagement.IMaintainOrganisationName")]
[module: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "HiiP.Framework.Security.UserManagement.IGISUserRoleAssignment")]
[module: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "HiiP.Framework.Security.UserManagement.IWFUserRoleAssignment")]
[module: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "HiiP.Framework.Security.UserManagement.IDMSUserRoleAssignment")]
[module: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "HiiP.Framework.Security.UserManagement.IMaintainOrganisationNameDetail")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.DevTreeNode.#get_PrimaryKey()")]
[module: SuppressMessage("HiiP.ExceptionHandling", "HP2001:ExceptionHandlingInPresenterNotAllowed", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.UserDetailPresenter.#SaveUser()", MessageId = "ExceptionHandlingInPresenterNotAllowed")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ForwardDestination.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.UserRoleAssignment.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.DMSUserRoleAssignment.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.BatchRoleAssignment.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.UserMaintenance.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.UserDetail.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ListOfFunctionAndDataFilter.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.MaintainOrganisationNameDetail.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.MaintainOrganisationName.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.RoleMaintenance.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.GISUserRoleAssignment.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.DelegationDetail.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.MaintainDelegation.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ListOfUserInRole.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.RoleDetail.#.ctor()")]

[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.WFUserRoleAssignment.#.ctor()")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ForwardDestination.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.UserRoleAssignment.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.DMSUserRoleAssignment.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.BatchRoleAssignment.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.UserMaintenance.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.UserDetail.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ListOfFunctionAndDataFilter.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.MaintainOrganisationNameDetail.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.MaintainOrganisationName.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.RoleMaintenance.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.GISUserRoleAssignment.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.DelegationDetail.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.MaintainDelegation.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ListOfUserInRole.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.RoleDetail.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.WFUserRoleAssignment.#Presenter")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowNewRoleMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowNewRoleMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowOrganisationMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowOrganisationMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowSecurityMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowSecurityMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowDelegationMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowDelegationMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowMaintainOrganisationMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowMaintainOrganisationMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowNewUserMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowNewUserMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowUserMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowUserMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowSearchRoleMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowSearchRoleMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowCreateDelegationMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowCreateDelegationMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowSearchUserMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowSearchUserMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowMaintainDelegationMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowMaintainDelegationMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowRoleMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.ModuleController.#ShowRoleMenu(System.Object,System.Object)", MessageId = "caller")]

[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.UserRoleAssignment.#DataFilterEntities")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.IRoleDetail.#ActionsInRole")]

[module: SuppressMessage("HiiP.Usages", "HP1005:AcceptCancelButtonNonexistence", Scope = "type", Target = "HiiP.Framework.Security.UserManagement.GISUserRoleAssignment", MessageId = "AcceptButtonNonexistence")]
[module: SuppressMessage("HiiP.Usages", "HP1005:AcceptCancelButtonNonexistence", Scope = "type", Target = "HiiP.Framework.Security.UserManagement.GISUserRoleAssignment", MessageId = "AcceptButtonNonexistence")]
[module: SuppressMessage("HiiP.Usages", "HP1005:AcceptCancelButtonNonexistence", Scope = "type", Target = "HiiP.Framework.Security.UserManagement.WFUserRoleAssignment", MessageId = "AcceptButtonNonexistence")]

[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.IUserRoleAssignment.#DataFilterEntities")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.RoleDetail.#ActionsInRole")]

[module: SuppressMessage("HiiP.ExceptionHandling", "HP1002:ExceptionHandlingInViewControlEventHandlerRequired", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.UserDetail.#btn_ok_Click(System.Object,System.EventArgs)", MessageId = "ExceptionHandlingInViewControlEventHandlerRequired")]
[module: SuppressMessage("HiiP.ExceptionHandling", "HP1001:ExceptionHandlingInViewOnLoadRequired", Scope = "member", Target = "HiiP.Framework.Security.UserManagement.UserDetail.#OnLoad(System.EventArgs)", MessageId = "ExceptionHandlingInViewOnLoadRequired")]