
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace HiiP.Framework.Security.UserManagement
{
    partial class ForwardDestination
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private ForwardDestinationPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.ValueListItem valueListItem1 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem2 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            this.ultraButtonOK = new Infragistics.Win.Misc.UltraButton();
            this.ultraButtonCancel = new Infragistics.Win.Misc.UltraButton();
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.ultraOptionSetType = new Infragistics.Win.UltraWinEditors.UltraOptionSet();
            this.ultraLabel2 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel3 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel4 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraComboEditorUnit = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.ultraComboEditorSubUnit = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.panelHeadOffice = new System.Windows.Forms.Panel();
            this.ultraComboEditorUser4HeadOffice = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.ultraLabel1 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel8 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraComboEditorBranch = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.ultraLabel6 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel7 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraComboEditorOffice = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.ultraComboEditorRegion = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.panelRegionalOffice = new System.Windows.Forms.Panel();
            this.ultraComboEditorUser4RegionalOffice = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.ultraLabel5 = new Infragistics.Win.Misc.UltraLabel();
            this.validationProvider1 = new Microsoft.Practices.EnterpriseLibrary.Validation.Integration.WinForms.ValidationProvider();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraOptionSetType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditorUnit)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditorSubUnit)).BeginInit();
            this.panelHeadOffice.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditorUser4HeadOffice)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditorBranch)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditorOffice)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditorRegion)).BeginInit();
            this.panelRegionalOffice.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditorUser4RegionalOffice)).BeginInit();
            this.SuspendLayout();
            // 
            // ultraButtonOK
            // 
            this.ultraButtonOK.Location = new System.Drawing.Point(129, 220);
            this.ultraButtonOK.Name = "ultraButtonOK";
            this.ultraButtonOK.Size = new System.Drawing.Size(87, 25);
            this.ultraButtonOK.TabIndex = 4;
            this.ultraButtonOK.Text = "OK";
            this.ultraButtonOK.Click += new System.EventHandler(this.ultraButtonOK_Click);
            // 
            // ultraButtonCancel
            // 
            this.ultraButtonCancel.Location = new System.Drawing.Point(241, 220);
            this.ultraButtonCancel.Name = "ultraButtonCancel";
            this.ultraButtonCancel.Size = new System.Drawing.Size(87, 25);
            this.ultraButtonCancel.TabIndex = 5;
            this.ultraButtonCancel.Text = "Cancel";
            this.ultraButtonCancel.Click += new System.EventHandler(this.ultraButtonCancel_Click);
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // ultraOptionSetType
            // 
            this.ultraOptionSetType.BorderStyle = Infragistics.Win.UIElementBorderStyle.None;
            valueListItem1.DataValue = "headoffice";
            valueListItem1.DisplayText = "Head office";
            valueListItem2.DataValue = "region";
            valueListItem2.DisplayText = "Regional office";
            this.ultraOptionSetType.Items.AddRange(new Infragistics.Win.ValueListItem[] {
            valueListItem1,
            valueListItem2});
            this.ultraOptionSetType.ItemSpacingVertical = 10;
            this.ultraOptionSetType.Location = new System.Drawing.Point(145, 20);
            this.ultraOptionSetType.Margin = new System.Windows.Forms.Padding(0);
            this.ultraOptionSetType.Name = "ultraOptionSetType";
            this.ultraOptionSetType.Size = new System.Drawing.Size(256, 30);
            this.ultraOptionSetType.TabIndex = 1;
            this.ultraOptionSetType.ValueChanged += new System.EventHandler(this.ultraOptionSetType_ValueChanged);
            // 
            // ultraLabel2
            // 
            appearance2.TextHAlignAsString = "Right";
            this.ultraLabel2.Appearance = appearance2;
            this.ultraLabel2.Location = new System.Drawing.Point(21, 24);
            this.ultraLabel2.Name = "ultraLabel2";
            this.ultraLabel2.Size = new System.Drawing.Size(86, 25);
            this.ultraLabel2.TabIndex = 0;
            this.ultraLabel2.Text = "Type";
            // 
            // ultraLabel3
            // 
            appearance1.TextHAlignAsString = "Right";
            this.ultraLabel3.Appearance = appearance1;
            this.ultraLabel3.Location = new System.Drawing.Point(12, 53);
            this.ultraLabel3.Name = "ultraLabel3";
            this.ultraLabel3.Size = new System.Drawing.Size(75, 25);
            this.ultraLabel3.TabIndex = 2;
            this.ultraLabel3.Text = "Unit";
            // 
            // ultraLabel4
            // 
            appearance9.TextHAlignAsString = "Right";
            this.ultraLabel4.Appearance = appearance9;
            this.ultraLabel4.Location = new System.Drawing.Point(12, 91);
            this.ultraLabel4.Name = "ultraLabel4";
            this.ultraLabel4.Size = new System.Drawing.Size(75, 25);
            this.ultraLabel4.TabIndex = 4;
            this.ultraLabel4.Text = "Sub Unit";
            // 
            // ultraComboEditorUnit
            // 
            this.ultraComboEditorUnit.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ultraComboEditorUnit.Location = new System.Drawing.Point(126, 49);
            this.ultraComboEditorUnit.Name = "ultraComboEditorUnit";
            this.ultraComboEditorUnit.Size = new System.Drawing.Size(254, 23);
            this.ultraComboEditorUnit.SyncWithCurrencyManager = false;
            this.ultraComboEditorUnit.TabIndex = 3;
            this.ultraComboEditorUnit.ValueChanged += new System.EventHandler(this.ultraComboEditorUnit_ValueChanged);
            // 
            // ultraComboEditorSubUnit
            // 
            this.ultraComboEditorSubUnit.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ultraComboEditorSubUnit.Location = new System.Drawing.Point(126, 87);
            this.ultraComboEditorSubUnit.Name = "ultraComboEditorSubUnit";
            this.ultraComboEditorSubUnit.Size = new System.Drawing.Size(254, 23);
            this.ultraComboEditorSubUnit.SyncWithCurrencyManager = false;
            this.ultraComboEditorSubUnit.TabIndex = 5;
            this.ultraComboEditorSubUnit.ValueChanged += new System.EventHandler(this.ultraComboEditorSubUnit_ValueChanged);
            // 
            // panelHeadOffice
            // 
            this.panelHeadOffice.Controls.Add(this.ultraComboEditorUser4HeadOffice);
            this.panelHeadOffice.Controls.Add(this.ultraLabel1);
            this.panelHeadOffice.Controls.Add(this.ultraLabel8);
            this.panelHeadOffice.Controls.Add(this.ultraComboEditorBranch);
            this.panelHeadOffice.Controls.Add(this.ultraLabel3);
            this.panelHeadOffice.Controls.Add(this.ultraLabel4);
            this.panelHeadOffice.Controls.Add(this.ultraComboEditorSubUnit);
            this.panelHeadOffice.Controls.Add(this.ultraComboEditorUnit);
            this.panelHeadOffice.Location = new System.Drawing.Point(21, 52);
            this.panelHeadOffice.Name = "panelHeadOffice";
            this.panelHeadOffice.Size = new System.Drawing.Size(422, 162);
            this.panelHeadOffice.TabIndex = 3;
            // 
            // ultraComboEditorUser4HeadOffice
            // 
            this.ultraComboEditorUser4HeadOffice.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ultraComboEditorUser4HeadOffice.Location = new System.Drawing.Point(125, 123);
            this.ultraComboEditorUser4HeadOffice.Name = "ultraComboEditorUser4HeadOffice";
            this.validationProvider1.SetPerformValidation(this.ultraComboEditorUser4HeadOffice, true);
            this.ultraComboEditorUser4HeadOffice.Size = new System.Drawing.Size(254, 23);
            this.validationProvider1.SetSourcePropertyName(this.ultraComboEditorUser4HeadOffice, "GroupUser");
            this.ultraComboEditorUser4HeadOffice.SyncWithCurrencyManager = false;
            this.ultraComboEditorUser4HeadOffice.TabIndex = 7;
            this.validationProvider1.SetValidatedProperty(this.ultraComboEditorUser4HeadOffice, "Value");
            // 
            // ultraLabel1
            // 
            appearance8.TextHAlignAsString = "Right";
            this.ultraLabel1.Appearance = appearance8;
            this.ultraLabel1.Location = new System.Drawing.Point(14, 16);
            this.ultraLabel1.Name = "ultraLabel1";
            this.ultraLabel1.Size = new System.Drawing.Size(75, 25);
            this.ultraLabel1.TabIndex = 0;
            this.ultraLabel1.Text = "Branch";
            // 
            // ultraLabel8
            // 
            appearance10.TextHAlignAsString = "Right";
            this.ultraLabel8.Appearance = appearance10;
            this.ultraLabel8.Location = new System.Drawing.Point(1, 127);
            this.ultraLabel8.Name = "ultraLabel8";
            this.ultraLabel8.Size = new System.Drawing.Size(86, 25);
            this.ultraLabel8.TabIndex = 6;
            this.ultraLabel8.Text = "* User";
            // 
            // ultraComboEditorBranch
            // 
            this.ultraComboEditorBranch.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ultraComboEditorBranch.Location = new System.Drawing.Point(126, 12);
            this.ultraComboEditorBranch.Name = "ultraComboEditorBranch";
            this.ultraComboEditorBranch.Size = new System.Drawing.Size(254, 23);
            this.ultraComboEditorBranch.SyncWithCurrencyManager = false;
            this.ultraComboEditorBranch.TabIndex = 1;
            this.ultraComboEditorBranch.ValueChanged += new System.EventHandler(this.ultraComboEditorBranch_ValueChanged);
            // 
            // ultraLabel6
            // 
            appearance6.TextHAlignAsString = "Right";
            this.ultraLabel6.Appearance = appearance6;
            this.ultraLabel6.Location = new System.Drawing.Point(14, 16);
            this.ultraLabel6.Name = "ultraLabel6";
            this.ultraLabel6.Size = new System.Drawing.Size(75, 25);
            this.ultraLabel6.TabIndex = 0;
            this.ultraLabel6.Text = "Region";
            // 
            // ultraLabel7
            // 
            appearance7.TextHAlignAsString = "Right";
            this.ultraLabel7.Appearance = appearance7;
            this.ultraLabel7.Location = new System.Drawing.Point(14, 53);
            this.ultraLabel7.Name = "ultraLabel7";
            this.ultraLabel7.Size = new System.Drawing.Size(75, 25);
            this.ultraLabel7.TabIndex = 0;
            this.ultraLabel7.Text = "Office";
            // 
            // ultraComboEditorOffice
            // 
            this.ultraComboEditorOffice.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ultraComboEditorOffice.Location = new System.Drawing.Point(126, 49);
            this.ultraComboEditorOffice.Name = "ultraComboEditorOffice";
            this.ultraComboEditorOffice.Size = new System.Drawing.Size(254, 23);
            this.ultraComboEditorOffice.SyncWithCurrencyManager = false;
            this.ultraComboEditorOffice.TabIndex = 3;
            this.ultraComboEditorOffice.ValueChanged += new System.EventHandler(this.ultraComboEditorOffice_ValueChanged);
            // 
            // ultraComboEditorRegion
            // 
            this.ultraComboEditorRegion.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ultraComboEditorRegion.Location = new System.Drawing.Point(126, 12);
            this.ultraComboEditorRegion.Name = "ultraComboEditorRegion";
            this.ultraComboEditorRegion.Size = new System.Drawing.Size(254, 23);
            this.ultraComboEditorRegion.SyncWithCurrencyManager = false;
            this.ultraComboEditorRegion.TabIndex = 1;
            this.ultraComboEditorRegion.ValueChanged += new System.EventHandler(this.ultraComboEditorRegion_ValueChanged);
            // 
            // panelRegionalOffice
            // 
            this.panelRegionalOffice.Controls.Add(this.ultraComboEditorUser4RegionalOffice);
            this.panelRegionalOffice.Controls.Add(this.ultraLabel5);
            this.panelRegionalOffice.Controls.Add(this.ultraLabel6);
            this.panelRegionalOffice.Controls.Add(this.ultraLabel7);
            this.panelRegionalOffice.Controls.Add(this.ultraComboEditorRegion);
            this.panelRegionalOffice.Controls.Add(this.ultraComboEditorOffice);
            this.panelRegionalOffice.Location = new System.Drawing.Point(22, 53);
            this.panelRegionalOffice.Name = "panelRegionalOffice";
            this.panelRegionalOffice.Size = new System.Drawing.Size(422, 129);
            this.panelRegionalOffice.TabIndex = 2;
            // 
            // ultraComboEditorUser4RegionalOffice
            // 
            this.ultraComboEditorUser4RegionalOffice.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ultraComboEditorUser4RegionalOffice.Location = new System.Drawing.Point(126, 87);
            this.ultraComboEditorUser4RegionalOffice.Name = "ultraComboEditorUser4RegionalOffice";
            this.validationProvider1.SetPerformValidation(this.ultraComboEditorUser4RegionalOffice, true);
            this.ultraComboEditorUser4RegionalOffice.Size = new System.Drawing.Size(254, 23);
            this.validationProvider1.SetSourcePropertyName(this.ultraComboEditorUser4RegionalOffice, "GroupUser");
            this.ultraComboEditorUser4RegionalOffice.SyncWithCurrencyManager = false;
            this.ultraComboEditorUser4RegionalOffice.TabIndex = 5;
            this.validationProvider1.SetValidatedProperty(this.ultraComboEditorUser4RegionalOffice, "Value");
            // 
            // ultraLabel5
            // 
            appearance3.TextHAlignAsString = "Right";
            this.ultraLabel5.Appearance = appearance3;
            this.ultraLabel5.Location = new System.Drawing.Point(2, 91);
            this.ultraLabel5.Name = "ultraLabel5";
            this.ultraLabel5.Size = new System.Drawing.Size(86, 25);
            this.ultraLabel5.TabIndex = 1;
            this.ultraLabel5.Text = "* User";
            // 
            // validationProvider1
            // 
            this.validationProvider1.ErrorProvider = this.errorProvider1;
            this.validationProvider1.RulesetName = "Forward Save Rule Set";
            this.validationProvider1.SourceTypeName = "HiiP.Foundation.Workflow.Interface.ValidationEntity.Forward, HiiP.Foundation.Work" +
                "flow.Interface";
            // 
            // ForwardDestination
            // 
            this.AcceptButton = this.ultraButtonOK;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Transparent;
            this.CancelButton = this.ultraButtonCancel;
            this.Controls.Add(this.panelRegionalOffice);
            this.Controls.Add(this.ultraLabel2);
            this.Controls.Add(this.ultraOptionSetType);
            this.Controls.Add(this.ultraButtonCancel);
            this.Controls.Add(this.ultraButtonOK);
            this.Controls.Add(this.panelHeadOffice);
            this.Name = "ForwardDestination";
            this.Size = new System.Drawing.Size(471, 271);
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraOptionSetType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditorUnit)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditorSubUnit)).EndInit();
            this.panelHeadOffice.ResumeLayout(false);
            this.panelHeadOffice.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditorUser4HeadOffice)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditorBranch)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditorOffice)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditorRegion)).EndInit();
            this.panelRegionalOffice.ResumeLayout(false);
            this.panelRegionalOffice.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraComboEditorUser4RegionalOffice)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraButton ultraButtonOK;
        private Infragistics.Win.Misc.UltraButton ultraButtonCancel;
        private System.Windows.Forms.ErrorProvider errorProvider1;
        private Infragistics.Win.UltraWinEditors.UltraOptionSet ultraOptionSetType;
        private Infragistics.Win.Misc.UltraLabel ultraLabel2;
        private Infragistics.Win.Misc.UltraLabel ultraLabel4;
        private Infragistics.Win.Misc.UltraLabel ultraLabel3;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ultraComboEditorSubUnit;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ultraComboEditorUnit;
        private System.Windows.Forms.Panel panelHeadOffice;
        private Infragistics.Win.Misc.UltraLabel ultraLabel6;
        private Infragistics.Win.Misc.UltraLabel ultraLabel7;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ultraComboEditorOffice;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ultraComboEditorRegion;
        private System.Windows.Forms.Panel panelRegionalOffice;
        private Microsoft.Practices.EnterpriseLibrary.Validation.Integration.WinForms.ValidationProvider validationProvider1;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ultraComboEditorUser4RegionalOffice;
        private Infragistics.Win.Misc.UltraLabel ultraLabel5;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ultraComboEditorUser4HeadOffice;
        private Infragistics.Win.Misc.UltraLabel ultraLabel1;
        private Infragistics.Win.Misc.UltraLabel ultraLabel8;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor ultraComboEditorBranch;
    }
}

