
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace HiiP.Framework.Settings
{
    partial class LoggingFilterMaintain
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private HiiP.Framework.Settings.LoggingFilterMaintainPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand1 = new Infragistics.Win.UltraWinGrid.UltraGridBand("Band 0", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn1 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("CATEGORY");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn2 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("USER_ID");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn3 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("FLAG");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn4 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("VERSION_NO");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn5 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("TRANSACTION_ID");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn6 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("CREATED_BY");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn7 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("CREATED_TIME");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn8 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("LAST_UPDATED_BY");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn9 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("LAST_UPDATED_TIME");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn10 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("USER_NAME", 0);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn11 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("Select", 1);
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.ValueListItem valueListItem1 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem2 = new Infragistics.Win.ValueListItem();
            this.ultraGroupBox2 = new Infragistics.Win.Misc.UltraGroupBox();
            this.ButtonDelete = new Infragistics.Win.Misc.UltraButton();
            this.btnInstrumentationAdd = new Infragistics.Win.Misc.UltraButton();
            this.ButtonClose = new Infragistics.Win.Misc.UltraButton();
            this.totalCount = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel9 = new Infragistics.Win.Misc.UltraLabel();
            this.GridViewLoggingFilter = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this.ultraGroupBox3 = new Infragistics.Win.Misc.UltraGroupBox();
            this.ultraOptionSetUsage = new Infragistics.Win.UltraWinEditors.UltraOptionSet();
            this.btnUsageSave = new Infragistics.Win.Misc.UltraButton();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox2)).BeginInit();
            this.ultraGroupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.GridViewLoggingFilter)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox3)).BeginInit();
            this.ultraGroupBox3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraOptionSetUsage)).BeginInit();
            this.SuspendLayout();
            // 
            // ultraGroupBox2
            // 
            this.ultraGroupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.ultraGroupBox2.Controls.Add(this.ButtonDelete);
            this.ultraGroupBox2.Controls.Add(this.btnInstrumentationAdd);
            this.ultraGroupBox2.Controls.Add(this.ButtonClose);
            this.ultraGroupBox2.Controls.Add(this.totalCount);
            this.ultraGroupBox2.Controls.Add(this.ultraLabel9);
            this.ultraGroupBox2.Controls.Add(this.GridViewLoggingFilter);
            this.ultraGroupBox2.Location = new System.Drawing.Point(3, 70);
            this.ultraGroupBox2.Name = "ultraGroupBox2";
            this.ultraGroupBox2.Size = new System.Drawing.Size(926, 573);
            this.ultraGroupBox2.TabIndex = 2;
            this.ultraGroupBox2.Text = "Instrumentation and performance logging";
            this.ultraGroupBox2.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
            // 
            // ButtonDelete
            // 
            this.ButtonDelete.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ButtonDelete.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ButtonDelete.Location = new System.Drawing.Point(766, 541);
            this.ButtonDelete.Name = "ButtonDelete";
            this.ButtonDelete.Size = new System.Drawing.Size(75, 25);
            this.ButtonDelete.TabIndex = 5;
            this.ButtonDelete.Text = "&Delete";
            this.ButtonDelete.Click += new System.EventHandler(this.ButtonDelete_Click);
            // 
            // btnInstrumentationAdd
            // 
            this.btnInstrumentationAdd.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnInstrumentationAdd.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.btnInstrumentationAdd.Location = new System.Drawing.Point(847, 22);
            this.btnInstrumentationAdd.Name = "btnInstrumentationAdd";
            this.btnInstrumentationAdd.Size = new System.Drawing.Size(75, 25);
            this.btnInstrumentationAdd.TabIndex = 2;
            this.btnInstrumentationAdd.Text = "&Add";
            this.btnInstrumentationAdd.Click += new System.EventHandler(this.btnInstrumentationAdd_Click);
            // 
            // ButtonClose
            // 
            this.ButtonClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ButtonClose.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ButtonClose.Location = new System.Drawing.Point(847, 541);
            this.ButtonClose.Name = "ButtonClose";
            this.ButtonClose.Size = new System.Drawing.Size(75, 25);
            this.ButtonClose.TabIndex = 4;
            this.ButtonClose.Text = "&Close";
            this.ButtonClose.Click += new System.EventHandler(this.ButtonClose_Click);
            // 
            // totalCount
            // 
            appearance10.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            this.totalCount.Appearance = appearance10;
            this.totalCount.Location = new System.Drawing.Point(94, 27);
            this.totalCount.Name = "totalCount";
            this.totalCount.Size = new System.Drawing.Size(100, 17);
            this.totalCount.TabIndex = 1;
            this.totalCount.Text = "0";
            // 
            // ultraLabel9
            // 
            appearance9.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            this.ultraLabel9.Appearance = appearance9;
            this.ultraLabel9.Location = new System.Drawing.Point(3, 27);
            this.ultraLabel9.Name = "ultraLabel9";
            this.ultraLabel9.Size = new System.Drawing.Size(93, 17);
            this.ultraLabel9.TabIndex = 0;
            this.ultraLabel9.Text = "Total records :";
            // 
            // GridViewLoggingFilter
            // 
            this.GridViewLoggingFilter.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            appearance1.BackColor = System.Drawing.SystemColors.Window;
            appearance1.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.GridViewLoggingFilter.DisplayLayout.Appearance = appearance1;
            this.GridViewLoggingFilter.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            ultraGridColumn1.CellActivation = Infragistics.Win.UltraWinGrid.Activation.NoEdit;
            ultraGridColumn1.Header.Caption = "Category";
            ultraGridColumn1.Header.VisiblePosition = 2;
            ultraGridColumn1.Width = 157;
            ultraGridColumn2.Header.VisiblePosition = 0;
            ultraGridColumn2.Hidden = true;
            ultraGridColumn3.CellActivation = Infragistics.Win.UltraWinGrid.Activation.NoEdit;
            ultraGridColumn3.Header.Caption = "On";
            ultraGridColumn3.Header.VisiblePosition = 5;
            ultraGridColumn3.Hidden = true;
            ultraGridColumn4.Header.VisiblePosition = 3;
            ultraGridColumn4.Hidden = true;
            ultraGridColumn5.Header.VisiblePosition = 6;
            ultraGridColumn5.Hidden = true;
            ultraGridColumn6.Header.VisiblePosition = 7;
            ultraGridColumn6.Hidden = true;
            ultraGridColumn7.Header.VisiblePosition = 8;
            ultraGridColumn7.Hidden = true;
            ultraGridColumn8.Header.VisiblePosition = 9;
            ultraGridColumn8.Hidden = true;
            ultraGridColumn9.Header.VisiblePosition = 10;
            ultraGridColumn9.Hidden = true;
            ultraGridColumn10.CellActivation = Infragistics.Win.UltraWinGrid.Activation.NoEdit;
            ultraGridColumn10.Header.Caption = "User name";
            ultraGridColumn10.Header.VisiblePosition = 4;
            ultraGridColumn11.DataType = typeof(bool);
            ultraGridColumn11.Header.Caption = "";
            ultraGridColumn11.Header.VisiblePosition = 1;
            ultraGridColumn11.Width = 35;
            ultraGridBand1.Columns.AddRange(new object[] {
            ultraGridColumn1,
            ultraGridColumn2,
            ultraGridColumn3,
            ultraGridColumn4,
            ultraGridColumn5,
            ultraGridColumn6,
            ultraGridColumn7,
            ultraGridColumn8,
            ultraGridColumn9,
            ultraGridColumn10,
            ultraGridColumn11});
            ultraGridBand1.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.GridViewLoggingFilter.DisplayLayout.BandsSerializer.Add(ultraGridBand1);
            this.GridViewLoggingFilter.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.GridViewLoggingFilter.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance3.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance3.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance3.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance3.BorderColor = System.Drawing.SystemColors.Window;
            this.GridViewLoggingFilter.DisplayLayout.GroupByBox.Appearance = appearance3;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.GridViewLoggingFilter.DisplayLayout.GroupByBox.BandLabelAppearance = appearance4;
            this.GridViewLoggingFilter.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance5.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance5.BackColor2 = System.Drawing.SystemColors.Control;
            appearance5.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance5.ForeColor = System.Drawing.SystemColors.GrayText;
            this.GridViewLoggingFilter.DisplayLayout.GroupByBox.PromptAppearance = appearance5;
            this.GridViewLoggingFilter.DisplayLayout.MaxColScrollRegions = 1;
            this.GridViewLoggingFilter.DisplayLayout.MaxRowScrollRegions = 1;
            appearance6.BackColor = System.Drawing.SystemColors.Window;
            appearance6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.GridViewLoggingFilter.DisplayLayout.Override.ActiveCellAppearance = appearance6;
            appearance7.BackColor = System.Drawing.SystemColors.Highlight;
            appearance7.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.GridViewLoggingFilter.DisplayLayout.Override.ActiveRowAppearance = appearance7;
            this.GridViewLoggingFilter.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.True;
            this.GridViewLoggingFilter.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.GridViewLoggingFilter.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance8.BackColor = System.Drawing.SystemColors.Window;
            this.GridViewLoggingFilter.DisplayLayout.Override.CardAreaAppearance = appearance8;
            appearance11.BorderColor = System.Drawing.Color.Silver;
            appearance11.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.GridViewLoggingFilter.DisplayLayout.Override.CellAppearance = appearance11;
            this.GridViewLoggingFilter.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.GridViewLoggingFilter.DisplayLayout.Override.CellPadding = 0;
            appearance12.BackColor = System.Drawing.SystemColors.Control;
            appearance12.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance12.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance12.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance12.BorderColor = System.Drawing.SystemColors.Window;
            this.GridViewLoggingFilter.DisplayLayout.Override.GroupByRowAppearance = appearance12;
            appearance16.TextHAlignAsString = "Left";
            this.GridViewLoggingFilter.DisplayLayout.Override.HeaderAppearance = appearance16;
            this.GridViewLoggingFilter.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.GridViewLoggingFilter.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance17.BackColor = System.Drawing.SystemColors.Window;
            appearance17.BorderColor = System.Drawing.Color.Silver;
            this.GridViewLoggingFilter.DisplayLayout.Override.RowAppearance = appearance17;
            this.GridViewLoggingFilter.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance27.BackColor = System.Drawing.SystemColors.ControlLight;
            this.GridViewLoggingFilter.DisplayLayout.Override.TemplateAddRowAppearance = appearance27;
            this.GridViewLoggingFilter.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.GridViewLoggingFilter.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.GridViewLoggingFilter.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.GridViewLoggingFilter.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.GridViewLoggingFilter.Font = new System.Drawing.Font("Tahoma", 8F);
            this.GridViewLoggingFilter.Location = new System.Drawing.Point(3, 53);
            this.GridViewLoggingFilter.Name = "GridViewLoggingFilter";
            this.GridViewLoggingFilter.Size = new System.Drawing.Size(919, 482);
            this.GridViewLoggingFilter.TabIndex = 3;
            this.GridViewLoggingFilter.Text = "ultraGrid1";
            this.GridViewLoggingFilter.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.GridViewLoggingFilter_InitializeRow);
            // 
            // ultraGroupBox3
            // 
            this.ultraGroupBox3.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.ultraGroupBox3.Controls.Add(this.ultraOptionSetUsage);
            this.ultraGroupBox3.Controls.Add(this.btnUsageSave);
            this.ultraGroupBox3.Location = new System.Drawing.Point(3, 0);
            this.ultraGroupBox3.Name = "ultraGroupBox3";
            this.ultraGroupBox3.Size = new System.Drawing.Size(926, 64);
            this.ultraGroupBox3.TabIndex = 1;
            this.ultraGroupBox3.Text = "Usage logging";
            this.ultraGroupBox3.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
            // 
            // ultraOptionSetUsage
            // 
            appearance2.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            this.ultraOptionSetUsage.Appearance = appearance2;
            this.ultraOptionSetUsage.BackColor = System.Drawing.Color.Transparent;
            this.ultraOptionSetUsage.BackColorInternal = System.Drawing.Color.Transparent;
            this.ultraOptionSetUsage.BorderStyle = Infragistics.Win.UIElementBorderStyle.None;
            this.ultraOptionSetUsage.GlyphStyle = Infragistics.Win.GlyphStyle.Office2007;
            valueListItem1.DataValue = true;
            valueListItem1.DisplayText = "On";
            valueListItem2.DataValue = false;
            valueListItem2.DisplayText = "Off";
            this.ultraOptionSetUsage.Items.AddRange(new Infragistics.Win.ValueListItem[] {
            valueListItem1,
            valueListItem2});
            this.ultraOptionSetUsage.Location = new System.Drawing.Point(107, 21);
            this.ultraOptionSetUsage.Name = "ultraOptionSetUsage";
            this.ultraOptionSetUsage.Size = new System.Drawing.Size(240, 22);
            this.ultraOptionSetUsage.TabIndex = 0;
            // 
            // btnUsageSave
            // 
            this.btnUsageSave.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnUsageSave.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.btnUsageSave.Location = new System.Drawing.Point(847, 33);
            this.btnUsageSave.Name = "btnUsageSave";
            this.btnUsageSave.Size = new System.Drawing.Size(75, 25);
            this.btnUsageSave.TabIndex = 1;
            this.btnUsageSave.Text = "Save";
            this.btnUsageSave.Click += new System.EventHandler(this.btnUsageSave_Click);
            // 
            // LoggingFilterMaintain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this.ButtonClose;
            this.CheckDirtyRequired = true;
            this.Controls.Add(this.ultraGroupBox3);
            this.Controls.Add(this.ultraGroupBox2);
            this.Key = "Logging Filter Maintenance";
            this.Name = "LoggingFilterMaintain";
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox2)).EndInit();
            this.ultraGroupBox2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.GridViewLoggingFilter)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox3)).EndInit();
            this.ultraGroupBox3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ultraOptionSetUsage)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox2;
        private Infragistics.Win.Misc.UltraButton ButtonClose;
        private Infragistics.Win.Misc.UltraLabel totalCount;
        private Infragistics.Win.Misc.UltraLabel ultraLabel9;
        private Infragistics.Win.UltraWinGrid.UltraGrid GridViewLoggingFilter;
        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox3;
        private Infragistics.Win.UltraWinEditors.UltraOptionSet ultraOptionSetUsage;
        private Infragistics.Win.Misc.UltraButton btnUsageSave;
        private Infragistics.Win.Misc.UltraButton btnInstrumentationAdd;
        private Infragistics.Win.Misc.UltraButton ButtonDelete;
    }
}

