
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace HiiP.Framework.Logging
{
    partial class AuditLogView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private HiiP.Framework.Logging.AuditLogViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand1 = new Infragistics.Win.UltraWinGrid.UltraGridBand("T_IC_AUDIT_LOG_QUERY", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn1 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("TRANSACTION_ID");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn2 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("USER_NAME");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn3 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("LOG_FUNCTION");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn4 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("LOG_TIME");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn5 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("TABLE_NAME");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn6 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("OPERATION");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn7 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("DEVICE");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn8 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("IP_ADDRESS");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn9 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("HOST_NAME");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn10 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("OPERATION_TIME");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn11 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("APP_VERSION");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn12 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("LOG_ID");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn13 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("LOG_SUB_ID");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn14 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("INDEX");
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            this.ultraGroupBox2 = new Infragistics.Win.Misc.UltraGroupBox();
            this.ultraButtonPrint = new Infragistics.Win.Misc.UltraButton();
            this._ultraProgressBarForSearch = new Infragistics.Win.UltraWinProgressBar.UltraProgressBar();
            this.ButtonClose = new Infragistics.Win.Misc.UltraButton();
            this.totalCount = new Infragistics.Win.Misc.UltraLabel();
            this.GridViewAuditLog = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this.ultraGroupBox1 = new Infragistics.Win.Misc.UltraGroupBox();
            this.comboOperationName = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.TextboxTableName = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel8 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel10 = new Infragistics.Win.Misc.UltraLabel();
            this.TextboxIPAddress = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.TextboxDevice = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel3 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel6 = new Infragistics.Win.Misc.UltraLabel();
            this.TextboxFunctionName = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.TextBoxHostName = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.TextBoxUseName = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.DateTimeEndTime = new Infragistics.Win.UltraWinEditors.UltraDateTimeEditor();
            this.DateTimeStartTime = new Infragistics.Win.UltraWinEditors.UltraDateTimeEditor();
            this.ultraLabel7 = new Infragistics.Win.Misc.UltraLabel();
            this.ButtonSearch = new Infragistics.Win.Misc.UltraButton();
            this.ButtonClear = new Infragistics.Win.Misc.UltraButton();
            this.ultraLabel5 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel4 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel2 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel1 = new Infragistics.Win.Misc.UltraLabel();
            this.validationProvider1 = new Microsoft.Practices.EnterpriseLibrary.Validation.Integration.WinForms.ValidationProvider();
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.ultraGridPrintDocument = new Infragistics.Win.UltraWinGrid.UltraGridPrintDocument(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox2)).BeginInit();
            this.ultraGroupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.GridViewAuditLog)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox1)).BeginInit();
            this.ultraGroupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.comboOperationName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextboxTableName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextboxIPAddress)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextboxDevice)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextboxFunctionName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxHostName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxUseName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DateTimeEndTime)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DateTimeStartTime)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.SuspendLayout();
            // 
            // ultraGroupBox2
            // 
            this.ultraGroupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.ultraGroupBox2.Controls.Add(this.ultraButtonPrint);
            this.ultraGroupBox2.Controls.Add(this._ultraProgressBarForSearch);
            this.ultraGroupBox2.Controls.Add(this.ButtonClose);
            this.ultraGroupBox2.Controls.Add(this.totalCount);
            this.ultraGroupBox2.Controls.Add(this.GridViewAuditLog);
            this.ultraGroupBox2.Location = new System.Drawing.Point(3, 148);
            this.ultraGroupBox2.Name = "ultraGroupBox2";
            this.ultraGroupBox2.Size = new System.Drawing.Size(904, 258);
            this.ultraGroupBox2.TabIndex = 1;
            this.ultraGroupBox2.Text = "Search result";
            this.ultraGroupBox2.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
            // 
            // ultraButtonPrint
            // 
            this.ultraButtonPrint.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ultraButtonPrint.Enabled = false;
            this.ultraButtonPrint.Location = new System.Drawing.Point(736, 226);
            this.ultraButtonPrint.Name = "ultraButtonPrint";
            this.ultraButtonPrint.Size = new System.Drawing.Size(87, 25);
            this.ultraButtonPrint.TabIndex = 2;
            this.ultraButtonPrint.Text = "&Print";
            this.ultraButtonPrint.Click += new System.EventHandler(this.ultraButtonPrint_Click);
            // 
            // _ultraProgressBarForSearch
            // 
            this._ultraProgressBarForSearch.BorderStyle = Infragistics.Win.UIElementBorderStyle.WindowsVista;
            this._ultraProgressBarForSearch.Location = new System.Drawing.Point(309, 27);
            this._ultraProgressBarForSearch.Name = "_ultraProgressBarForSearch";
            this._ultraProgressBarForSearch.Size = new System.Drawing.Size(171, 18);
            this._ultraProgressBarForSearch.Style = Infragistics.Win.UltraWinProgressBar.ProgressBarStyle.Office2007Continuous;
            this._ultraProgressBarForSearch.TabIndex = 16;
            this._ultraProgressBarForSearch.Text = "[Formatted]";
            this._ultraProgressBarForSearch.Visible = false;
            // 
            // ButtonClose
            // 
            this.ButtonClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ButtonClose.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ButtonClose.Location = new System.Drawing.Point(826, 226);
            this.ButtonClose.Name = "ButtonClose";
            this.ButtonClose.Size = new System.Drawing.Size(87, 25);
            this.ButtonClose.TabIndex = 3;
            this.ButtonClose.Text = "&Close";
            this.ButtonClose.Click += new System.EventHandler(this.ButtonClose_Click);
            // 
            // totalCount
            // 
            appearance9.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            this.totalCount.Appearance = appearance9;
            this.totalCount.AutoSize = true;
            this.totalCount.Location = new System.Drawing.Point(3, 27);
            this.totalCount.Name = "totalCount";
            this.totalCount.Size = new System.Drawing.Size(96, 16);
            this.totalCount.TabIndex = 0;
            this.totalCount.Text = "Total record(s):0";
            // 
            // GridViewAuditLog
            // 
            this.GridViewAuditLog.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            appearance10.BackColor = System.Drawing.SystemColors.Window;
            appearance10.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.GridViewAuditLog.DisplayLayout.Appearance = appearance10;
            this.GridViewAuditLog.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            ultraGridColumn1.CellActivation = Infragistics.Win.UltraWinGrid.Activation.NoEdit;
            ultraGridColumn1.Header.Caption = "Transaction ID";
            ultraGridColumn1.Header.VisiblePosition = 0;
            ultraGridColumn2.CellActivation = Infragistics.Win.UltraWinGrid.Activation.NoEdit;
            ultraGridColumn2.Header.Caption = "User ID";
            ultraGridColumn2.Header.VisiblePosition = 2;
            ultraGridColumn3.CellActivation = Infragistics.Win.UltraWinGrid.Activation.NoEdit;
            ultraGridColumn3.Header.Caption = "Function ID";
            ultraGridColumn3.Header.VisiblePosition = 1;
            ultraGridColumn4.CellActivation = Infragistics.Win.UltraWinGrid.Activation.NoEdit;
            ultraGridColumn4.Format = "G";
            ultraGridColumn4.Header.Caption = "Date & Time";
            ultraGridColumn4.Header.VisiblePosition = 3;
            ultraGridColumn5.CellActivation = Infragistics.Win.UltraWinGrid.Activation.NoEdit;
            ultraGridColumn5.Header.Caption = "Table name /Action log";
            ultraGridColumn5.Header.VisiblePosition = 4;
            ultraGridColumn5.Width = 200;
            ultraGridColumn6.CellActivation = Infragistics.Win.UltraWinGrid.Activation.NoEdit;
            ultraGridColumn6.Header.Caption = "Operation";
            ultraGridColumn6.Header.VisiblePosition = 5;
            ultraGridColumn7.CellActivation = Infragistics.Win.UltraWinGrid.Activation.NoEdit;
            ultraGridColumn7.Header.Caption = "Device";
            ultraGridColumn7.Header.VisiblePosition = 12;
            ultraGridColumn8.CellActivation = Infragistics.Win.UltraWinGrid.Activation.NoEdit;
            ultraGridColumn8.Header.Caption = "IP address";
            ultraGridColumn8.Header.VisiblePosition = 9;
            ultraGridColumn9.CellActivation = Infragistics.Win.UltraWinGrid.Activation.NoEdit;
            ultraGridColumn9.Header.Caption = "Host name";
            ultraGridColumn9.Header.VisiblePosition = 8;
            ultraGridColumn10.Header.VisiblePosition = 10;
            ultraGridColumn10.Hidden = true;
            ultraGridColumn11.Header.VisiblePosition = 11;
            ultraGridColumn11.Hidden = true;
            ultraGridColumn12.Header.VisiblePosition = 6;
            ultraGridColumn12.Hidden = true;
            ultraGridColumn13.Header.VisiblePosition = 7;
            ultraGridColumn13.Hidden = true;
            ultraGridColumn14.Header.VisiblePosition = 13;
            ultraGridColumn14.Hidden = true;
            ultraGridBand1.Columns.AddRange(new object[] {
            ultraGridColumn1,
            ultraGridColumn2,
            ultraGridColumn3,
            ultraGridColumn4,
            ultraGridColumn5,
            ultraGridColumn6,
            ultraGridColumn7,
            ultraGridColumn8,
            ultraGridColumn9,
            ultraGridColumn10,
            ultraGridColumn11,
            ultraGridColumn12,
            ultraGridColumn13,
            ultraGridColumn14});
            ultraGridBand1.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            ultraGridBand1.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            ultraGridBand1.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.GridViewAuditLog.DisplayLayout.BandsSerializer.Add(ultraGridBand1);
            this.GridViewAuditLog.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.GridViewAuditLog.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance24.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance24.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance24.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance24.BorderColor = System.Drawing.SystemColors.Window;
            this.GridViewAuditLog.DisplayLayout.GroupByBox.Appearance = appearance24;
            appearance25.ForeColor = System.Drawing.SystemColors.GrayText;
            this.GridViewAuditLog.DisplayLayout.GroupByBox.BandLabelAppearance = appearance25;
            this.GridViewAuditLog.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance26.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance26.BackColor2 = System.Drawing.SystemColors.Control;
            appearance26.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance26.ForeColor = System.Drawing.SystemColors.GrayText;
            this.GridViewAuditLog.DisplayLayout.GroupByBox.PromptAppearance = appearance26;
            this.GridViewAuditLog.DisplayLayout.MaxColScrollRegions = 1;
            this.GridViewAuditLog.DisplayLayout.MaxRowScrollRegions = 1;
            appearance27.BackColor = System.Drawing.SystemColors.Window;
            appearance27.ForeColor = System.Drawing.SystemColors.ControlText;
            this.GridViewAuditLog.DisplayLayout.Override.ActiveCellAppearance = appearance27;
            appearance28.BackColor = System.Drawing.SystemColors.Highlight;
            appearance28.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.GridViewAuditLog.DisplayLayout.Override.ActiveRowAppearance = appearance28;
            this.GridViewAuditLog.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.True;
            this.GridViewAuditLog.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.GridViewAuditLog.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance29.BackColor = System.Drawing.SystemColors.Window;
            this.GridViewAuditLog.DisplayLayout.Override.CardAreaAppearance = appearance29;
            appearance30.BorderColor = System.Drawing.Color.Silver;
            appearance30.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.GridViewAuditLog.DisplayLayout.Override.CellAppearance = appearance30;
            this.GridViewAuditLog.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.GridViewAuditLog.DisplayLayout.Override.CellPadding = 0;
            appearance31.BackColor = System.Drawing.SystemColors.Control;
            appearance31.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance31.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance31.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance31.BorderColor = System.Drawing.SystemColors.Window;
            this.GridViewAuditLog.DisplayLayout.Override.GroupByRowAppearance = appearance31;
            appearance32.TextHAlignAsString = "Left";
            this.GridViewAuditLog.DisplayLayout.Override.HeaderAppearance = appearance32;
            this.GridViewAuditLog.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.GridViewAuditLog.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance33.BackColor = System.Drawing.SystemColors.Window;
            appearance33.BorderColor = System.Drawing.Color.Silver;
            this.GridViewAuditLog.DisplayLayout.Override.RowAppearance = appearance33;
            this.GridViewAuditLog.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance34.BackColor = System.Drawing.SystemColors.ControlLight;
            this.GridViewAuditLog.DisplayLayout.Override.TemplateAddRowAppearance = appearance34;
            this.GridViewAuditLog.DisplayLayout.Override.WrapHeaderText = Infragistics.Win.DefaultableBoolean.True;
            this.GridViewAuditLog.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.GridViewAuditLog.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.GridViewAuditLog.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.GridViewAuditLog.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.GridViewAuditLog.Font = new System.Drawing.Font("Tahoma", 8F);
            this.GridViewAuditLog.Location = new System.Drawing.Point(3, 53);
            this.GridViewAuditLog.Name = "GridViewAuditLog";
            this.GridViewAuditLog.Size = new System.Drawing.Size(897, 167);
            this.GridViewAuditLog.TabIndex = 1;
            this.GridViewAuditLog.Text = "ultraGrid1";
            this.GridViewAuditLog.KeyDown += new System.Windows.Forms.KeyEventHandler(this.GridViewAuditLog_KeyDown);
            this.GridViewAuditLog.DoubleClickRow += new Infragistics.Win.UltraWinGrid.DoubleClickRowEventHandler(this.GridViewAuditLog_DoubleClickRow);
            // 
            // ultraGroupBox1
            // 
            this.ultraGroupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.ultraGroupBox1.Controls.Add(this.comboOperationName);
            this.ultraGroupBox1.Controls.Add(this.TextboxTableName);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel8);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel10);
            this.ultraGroupBox1.Controls.Add(this.TextboxIPAddress);
            this.ultraGroupBox1.Controls.Add(this.TextboxDevice);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel3);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel6);
            this.ultraGroupBox1.Controls.Add(this.TextboxFunctionName);
            this.ultraGroupBox1.Controls.Add(this.TextBoxHostName);
            this.ultraGroupBox1.Controls.Add(this.TextBoxUseName);
            this.ultraGroupBox1.Controls.Add(this.DateTimeEndTime);
            this.ultraGroupBox1.Controls.Add(this.DateTimeStartTime);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel7);
            this.ultraGroupBox1.Controls.Add(this.ButtonSearch);
            this.ultraGroupBox1.Controls.Add(this.ButtonClear);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel5);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel4);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel2);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel1);
            this.ultraGroupBox1.Location = new System.Drawing.Point(3, 3);
            this.ultraGroupBox1.Name = "ultraGroupBox1";
            this.ultraGroupBox1.Size = new System.Drawing.Size(904, 139);
            this.ultraGroupBox1.TabIndex = 0;
            this.ultraGroupBox1.Text = "Search criteria";
            this.ultraGroupBox1.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
            // 
            // comboOperationName
            // 
            this.comboOperationName.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.comboOperationName.Location = new System.Drawing.Point(703, 80);
            this.comboOperationName.Name = "comboOperationName";
            this.comboOperationName.Size = new System.Drawing.Size(144, 23);
            this.comboOperationName.SyncWithCurrencyManager = false;
            this.comboOperationName.TabIndex = 18;
            // 
            // TextboxTableName
            // 
            this.TextboxTableName.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextboxTableName.Location = new System.Drawing.Point(703, 53);
            this.TextboxTableName.Name = "TextboxTableName";
            this.TextboxTableName.Size = new System.Drawing.Size(188, 23);
            this.TextboxTableName.TabIndex = 11;
            // 
            // ultraLabel8
            // 
            appearance15.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance15.TextHAlignAsString = "Right";
            this.ultraLabel8.Appearance = appearance15;
            this.ultraLabel8.Location = new System.Drawing.Point(601, 84);
            this.ultraLabel8.Name = "ultraLabel8";
            this.ultraLabel8.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel8.TabIndex = 17;
            this.ultraLabel8.Text = "Operation";
            // 
            // ultraLabel10
            // 
            appearance2.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance2.TextHAlignAsString = "Right";
            this.ultraLabel10.Appearance = appearance2;
            this.ultraLabel10.Location = new System.Drawing.Point(596, 57);
            this.ultraLabel10.Name = "ultraLabel10";
            this.ultraLabel10.Size = new System.Drawing.Size(101, 25);
            this.ultraLabel10.TabIndex = 10;
            this.ultraLabel10.Text = "Table name";
            // 
            // TextboxIPAddress
            // 
            this.TextboxIPAddress.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextboxIPAddress.Location = new System.Drawing.Point(114, 80);
            this.TextboxIPAddress.Name = "TextboxIPAddress";
            this.TextboxIPAddress.Size = new System.Drawing.Size(188, 23);
            this.TextboxIPAddress.TabIndex = 13;
            // 
            // TextboxDevice
            // 
            this.TextboxDevice.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextboxDevice.Location = new System.Drawing.Point(401, 80);
            this.TextboxDevice.Name = "TextboxDevice";
            this.TextboxDevice.Size = new System.Drawing.Size(188, 23);
            this.TextboxDevice.TabIndex = 16;
            // 
            // ultraLabel3
            // 
            appearance3.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance3.TextHAlignAsString = "Right";
            this.ultraLabel3.Appearance = appearance3;
            this.ultraLabel3.Location = new System.Drawing.Point(298, 84);
            this.ultraLabel3.Name = "ultraLabel3";
            this.ultraLabel3.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel3.TabIndex = 15;
            this.ultraLabel3.Text = "Device";
            // 
            // ultraLabel6
            // 
            appearance4.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance4.TextHAlignAsString = "Right";
            this.ultraLabel6.Appearance = appearance4;
            this.ultraLabel6.Location = new System.Drawing.Point(7, 84);
            this.ultraLabel6.Name = "ultraLabel6";
            this.ultraLabel6.Size = new System.Drawing.Size(101, 25);
            this.ultraLabel6.TabIndex = 12;
            this.ultraLabel6.Text = "IP address";
            // 
            // TextboxFunctionName
            // 
            this.TextboxFunctionName.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextboxFunctionName.Location = new System.Drawing.Point(115, 53);
            this.TextboxFunctionName.Name = "TextboxFunctionName";
            this.TextboxFunctionName.Size = new System.Drawing.Size(188, 23);
            this.TextboxFunctionName.TabIndex = 7;
            // 
            // TextBoxHostName
            // 
            this.TextBoxHostName.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxHostName.Location = new System.Drawing.Point(402, 53);
            this.TextBoxHostName.Name = "TextBoxHostName";
            this.TextBoxHostName.Size = new System.Drawing.Size(188, 23);
            this.TextBoxHostName.TabIndex = 9;
            // 
            // TextBoxUseName
            // 
            this.TextBoxUseName.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxUseName.Location = new System.Drawing.Point(703, 25);
            this.TextBoxUseName.Name = "TextBoxUseName";
            this.TextBoxUseName.Size = new System.Drawing.Size(188, 23);
            this.TextBoxUseName.TabIndex = 5;
            // 
            // DateTimeEndTime
            // 
            this.DateTimeEndTime.DateTime = new System.DateTime(2008, 8, 11, 0, 0, 0, 0);
            this.DateTimeEndTime.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.DateTimeEndTime.Location = new System.Drawing.Point(402, 25);
            this.DateTimeEndTime.MaskInput = "{date} {longtime}";
            this.DateTimeEndTime.Name = "DateTimeEndTime";
            this.DateTimeEndTime.Nullable = false;
            this.validationProvider1.SetPerformValidation(this.DateTimeEndTime, true);
            this.DateTimeEndTime.Size = new System.Drawing.Size(188, 23);
            this.validationProvider1.SetSourcePropertyName(this.DateTimeEndTime, "EndTime");
            this.DateTimeEndTime.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.DateTimeEndTime.TabIndex = 3;
            this.DateTimeEndTime.Value = new System.DateTime(2008, 8, 11, 0, 0, 0, 0);
            // 
            // DateTimeStartTime
            // 
            this.DateTimeStartTime.DateTime = new System.DateTime(2008, 8, 11, 0, 0, 0, 0);
            this.DateTimeStartTime.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.DateTimeStartTime.Location = new System.Drawing.Point(115, 25);
            this.DateTimeStartTime.MaskInput = "{date} {longtime}";
            this.DateTimeStartTime.Name = "DateTimeStartTime";
            this.DateTimeStartTime.Nullable = false;
            this.validationProvider1.SetPerformValidation(this.DateTimeStartTime, true);
            this.DateTimeStartTime.Size = new System.Drawing.Size(188, 23);
            this.validationProvider1.SetSourcePropertyName(this.DateTimeStartTime, "StartTime");
            this.DateTimeStartTime.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.DateTimeStartTime.TabIndex = 1;
            this.DateTimeStartTime.Value = new System.DateTime(2008, 8, 11, 0, 0, 0, 0);
            // 
            // ultraLabel7
            // 
            appearance14.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance14.TextHAlignAsString = "Right";
            this.ultraLabel7.Appearance = appearance14;
            this.ultraLabel7.Location = new System.Drawing.Point(299, 29);
            this.ultraLabel7.Name = "ultraLabel7";
            this.ultraLabel7.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel7.TabIndex = 2;
            this.ultraLabel7.Text = "* End time";
            // 
            // ButtonSearch
            // 
            this.ButtonSearch.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ButtonSearch.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ButtonSearch.Location = new System.Drawing.Point(730, 109);
            this.ButtonSearch.Name = "ButtonSearch";
            this.ButtonSearch.Size = new System.Drawing.Size(87, 25);
            this.ButtonSearch.TabIndex = 19;
            this.ButtonSearch.Text = "&Search";
            this.ButtonSearch.Click += new System.EventHandler(this.ButtonSearch_Click);
            // 
            // ButtonClear
            // 
            this.ButtonClear.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ButtonClear.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ButtonClear.Location = new System.Drawing.Point(824, 109);
            this.ButtonClear.Name = "ButtonClear";
            this.ButtonClear.Size = new System.Drawing.Size(87, 25);
            this.ButtonClear.TabIndex = 20;
            this.ButtonClear.Text = "&Reset";
            this.ButtonClear.Click += new System.EventHandler(this.ButtonClear_Click);
            // 
            // ultraLabel5
            // 
            appearance5.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance5.TextHAlignAsString = "Right";
            this.ultraLabel5.Appearance = appearance5;
            this.ultraLabel5.Location = new System.Drawing.Point(299, 57);
            this.ultraLabel5.Name = "ultraLabel5";
            this.ultraLabel5.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel5.TabIndex = 8;
            this.ultraLabel5.Text = "Host name";
            // 
            // ultraLabel4
            // 
            appearance6.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance6.TextHAlignAsString = "Right";
            this.ultraLabel4.Appearance = appearance6;
            this.ultraLabel4.Location = new System.Drawing.Point(8, 57);
            this.ultraLabel4.Name = "ultraLabel4";
            this.ultraLabel4.Size = new System.Drawing.Size(101, 25);
            this.ultraLabel4.TabIndex = 6;
            this.ultraLabel4.Text = "Function ID";
            // 
            // ultraLabel2
            // 
            appearance1.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance1.TextHAlignAsString = "Right";
            this.ultraLabel2.Appearance = appearance1;
            this.ultraLabel2.Location = new System.Drawing.Point(613, 29);
            this.ultraLabel2.Name = "ultraLabel2";
            this.ultraLabel2.Size = new System.Drawing.Size(84, 25);
            this.ultraLabel2.TabIndex = 4;
            this.ultraLabel2.Text = "User ID";
            // 
            // ultraLabel1
            // 
            appearance13.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance13.TextHAlignAsString = "Right";
            this.ultraLabel1.Appearance = appearance13;
            this.ultraLabel1.Location = new System.Drawing.Point(25, 29);
            this.ultraLabel1.Name = "ultraLabel1";
            this.ultraLabel1.Size = new System.Drawing.Size(84, 25);
            this.ultraLabel1.TabIndex = 0;
            this.ultraLabel1.Text = "* Start time";
            // 
            // validationProvider1
            // 
            this.validationProvider1.ErrorProvider = this.errorProvider1;
            this.validationProvider1.RulesetName = "Date Time Compare Set";
            this.validationProvider1.SourceTypeName = "HiiP.Framework.Logging.Interface.ValidationEntity.DateTimeCompare,HiiP.Framework." +
                "Logging.Interface";
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // ultraGridPrintDocument
            // 
            this.ultraGridPrintDocument.Grid = this.GridViewAuditLog;
            // 
            // AuditLogView
            // 
            this.AcceptButton = this.ButtonSearch;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            this.AutoScrollMinSize = new System.Drawing.Size(911, 408);
            this.CancelButton = this.ButtonClose;
            this.Controls.Add(this.ultraGroupBox2);
            this.Controls.Add(this.ultraGroupBox1);
            this.Key = "Audit Log View";
            this.Name = "AuditLogView";
            this.Size = new System.Drawing.Size(754, 345);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox2)).EndInit();
            this.ultraGroupBox2.ResumeLayout(false);
            this.ultraGroupBox2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.GridViewAuditLog)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox1)).EndInit();
            this.ultraGroupBox1.ResumeLayout(false);
            this.ultraGroupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.comboOperationName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextboxTableName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextboxIPAddress)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextboxDevice)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextboxFunctionName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxHostName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxUseName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DateTimeEndTime)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DateTimeStartTime)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox2;
        private Infragistics.Win.Misc.UltraButton ButtonClose;
        private Infragistics.Win.Misc.UltraLabel totalCount;
        private Infragistics.Win.UltraWinGrid.UltraGrid GridViewAuditLog;
        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox1;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxHostName;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxUseName;
        private Infragistics.Win.UltraWinEditors.UltraDateTimeEditor DateTimeEndTime;
        private Infragistics.Win.UltraWinEditors.UltraDateTimeEditor DateTimeStartTime;
        private Infragistics.Win.Misc.UltraLabel ultraLabel7;
        private Infragistics.Win.Misc.UltraButton ButtonSearch;
        private Infragistics.Win.Misc.UltraButton ButtonClear;
        private Infragistics.Win.Misc.UltraLabel ultraLabel5;
        private Infragistics.Win.Misc.UltraLabel ultraLabel4;
        private Infragistics.Win.Misc.UltraLabel ultraLabel2;
        private Infragistics.Win.Misc.UltraLabel ultraLabel1;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextboxFunctionName;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextboxTableName;
        private Infragistics.Win.Misc.UltraLabel ultraLabel8;
        private Infragistics.Win.Misc.UltraLabel ultraLabel10;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextboxIPAddress;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextboxDevice;
        private Infragistics.Win.Misc.UltraLabel ultraLabel3;
        private Infragistics.Win.Misc.UltraLabel ultraLabel6;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor comboOperationName;
        private Infragistics.Win.UltraWinProgressBar.UltraProgressBar _ultraProgressBarForSearch;
        private Microsoft.Practices.EnterpriseLibrary.Validation.Integration.WinForms.ValidationProvider validationProvider1;
        private System.Windows.Forms.ErrorProvider errorProvider1;
        private Infragistics.Win.Misc.UltraButton ultraButtonPrint;
        private Infragistics.Win.UltraWinGrid.UltraGridPrintDocument ultraGridPrintDocument;
    }
}

