
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace HiiP.Framework.ExceptionHandling
{
    partial class ExceptionLogDetailView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private HiiP.Framework.ExceptionHandling.ExceptionLogDetailViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            this.ultraGroupBox1 = new Infragistics.Win.Misc.UltraGroupBox();
            this.TextBoxContent = new Infragistics.Win.FormattedLinkLabel.UltraFormattedTextEditor();
            this.ButtonClose = new Infragistics.Win.Misc.UltraButton();
            this.ultraLabel9 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxPCName = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel8 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxIPAddress = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel7 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxComponent = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel6 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxOffice = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel5 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxUserRoles = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel4 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxUserName = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel3 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxSeverity = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel2 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxTime = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel1 = new Infragistics.Win.Misc.UltraLabel();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox1)).BeginInit();
            this.ultraGroupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxPCName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxIPAddress)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxComponent)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxOffice)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxUserRoles)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxUserName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxSeverity)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxTime)).BeginInit();
            this.SuspendLayout();
            // 
            // ultraGroupBox1
            // 
            this.ultraGroupBox1.Controls.Add(this.TextBoxContent);
            this.ultraGroupBox1.Controls.Add(this.ButtonClose);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel9);
            this.ultraGroupBox1.Controls.Add(this.TextBoxPCName);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel8);
            this.ultraGroupBox1.Controls.Add(this.TextBoxIPAddress);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel7);
            this.ultraGroupBox1.Controls.Add(this.TextBoxComponent);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel6);
            this.ultraGroupBox1.Controls.Add(this.TextBoxOffice);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel5);
            this.ultraGroupBox1.Controls.Add(this.TextBoxUserRoles);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel4);
            this.ultraGroupBox1.Controls.Add(this.TextBoxUserName);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel3);
            this.ultraGroupBox1.Controls.Add(this.TextBoxSeverity);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel2);
            this.ultraGroupBox1.Controls.Add(this.TextBoxTime);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel1);
            this.ultraGroupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox1.Location = new System.Drawing.Point(0, 0);
            this.ultraGroupBox1.Name = "ultraGroupBox1";
            this.ultraGroupBox1.Size = new System.Drawing.Size(978, 513);
            this.ultraGroupBox1.TabIndex = 0;
            this.ultraGroupBox1.Text = "Exception log details";
            this.ultraGroupBox1.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
            // 
            // TextBoxContent
            // 
            this.TextBoxContent.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.TextBoxContent.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxContent.Location = new System.Drawing.Point(77, 163);
            this.TextBoxContent.Name = "TextBoxContent";
            this.TextBoxContent.ReadOnly = true;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2007;
            this.TextBoxContent.ScrollBarLook = scrollBarLook1;
            this.TextBoxContent.Size = new System.Drawing.Size(894, 321);
            this.TextBoxContent.TabIndex = 17;
            this.TextBoxContent.Value = "";
            // 
            // ButtonClose
            // 
            this.ButtonClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ButtonClose.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ButtonClose.Location = new System.Drawing.Point(884, 481);
            this.ButtonClose.Name = "ButtonClose";
            this.ButtonClose.Size = new System.Drawing.Size(87, 25);
            this.ButtonClose.TabIndex = 18;
            this.ButtonClose.Text = "&Close";
            this.ButtonClose.Click += new System.EventHandler(this.ButtonClose_Click);
            // 
            // ultraLabel9
            // 
            appearance1.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance1.TextHAlignAsString = "Right";
            this.ultraLabel9.Appearance = appearance1;
            this.ultraLabel9.AutoSize = true;
            this.ultraLabel9.Location = new System.Drawing.Point(27, 167);
            this.ultraLabel9.Name = "ultraLabel9";
            this.ultraLabel9.Size = new System.Drawing.Size(47, 16);
            this.ultraLabel9.TabIndex = 16;
            this.ultraLabel9.Text = "Content";
            // 
            // TextBoxPCName
            // 
            this.TextBoxPCName.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxPCName.Location = new System.Drawing.Point(621, 130);
            this.TextBoxPCName.Name = "TextBoxPCName";
            this.TextBoxPCName.ReadOnly = true;
            this.TextBoxPCName.Size = new System.Drawing.Size(350, 23);
            this.TextBoxPCName.TabIndex = 15;
            // 
            // ultraLabel8
            // 
            appearance9.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance9.TextHAlignAsString = "Right";
            this.ultraLabel8.Appearance = appearance9;
            this.ultraLabel8.AutoSize = true;
            this.ultraLabel8.Location = new System.Drawing.Point(532, 134);
            this.ultraLabel8.Name = "ultraLabel8";
            this.ultraLabel8.Size = new System.Drawing.Size(83, 16);
            this.ultraLabel8.TabIndex = 14;
            this.ultraLabel8.Text = "Machine name";
            // 
            // TextBoxIPAddress
            // 
            this.TextBoxIPAddress.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxIPAddress.Location = new System.Drawing.Point(77, 130);
            this.TextBoxIPAddress.Name = "TextBoxIPAddress";
            this.TextBoxIPAddress.ReadOnly = true;
            this.TextBoxIPAddress.Size = new System.Drawing.Size(350, 23);
            this.TextBoxIPAddress.TabIndex = 13;
            // 
            // ultraLabel7
            // 
            appearance6.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance6.TextHAlignAsString = "Right";
            this.ultraLabel7.Appearance = appearance6;
            this.ultraLabel7.AutoSize = true;
            this.ultraLabel7.Location = new System.Drawing.Point(12, 134);
            this.ultraLabel7.Name = "ultraLabel7";
            this.ultraLabel7.Size = new System.Drawing.Size(62, 16);
            this.ultraLabel7.TabIndex = 12;
            this.ultraLabel7.Text = "IP address";
            // 
            // TextBoxComponent
            // 
            this.TextBoxComponent.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxComponent.Location = new System.Drawing.Point(621, 97);
            this.TextBoxComponent.Name = "TextBoxComponent";
            this.TextBoxComponent.ReadOnly = true;
            this.TextBoxComponent.Size = new System.Drawing.Size(350, 23);
            this.TextBoxComponent.TabIndex = 11;
            // 
            // ultraLabel6
            // 
            appearance7.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance7.TextHAlignAsString = "Right";
            this.ultraLabel6.Appearance = appearance7;
            this.ultraLabel6.AutoSize = true;
            this.ultraLabel6.Location = new System.Drawing.Point(548, 101);
            this.ultraLabel6.Name = "ultraLabel6";
            this.ultraLabel6.Size = new System.Drawing.Size(67, 16);
            this.ultraLabel6.TabIndex = 10;
            this.ultraLabel6.Text = "Component";
            // 
            // TextBoxOffice
            // 
            this.TextBoxOffice.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxOffice.Location = new System.Drawing.Point(77, 97);
            this.TextBoxOffice.Name = "TextBoxOffice";
            this.TextBoxOffice.ReadOnly = true;
            this.TextBoxOffice.Size = new System.Drawing.Size(350, 23);
            this.TextBoxOffice.TabIndex = 9;
            // 
            // ultraLabel5
            // 
            appearance8.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance8.TextHAlignAsString = "Right";
            this.ultraLabel5.Appearance = appearance8;
            this.ultraLabel5.AutoSize = true;
            this.ultraLabel5.Location = new System.Drawing.Point(38, 101);
            this.ultraLabel5.Name = "ultraLabel5";
            this.ultraLabel5.Size = new System.Drawing.Size(36, 16);
            this.ultraLabel5.TabIndex = 8;
            this.ultraLabel5.Text = "Office";
            // 
            // TextBoxUserRoles
            // 
            this.TextBoxUserRoles.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxUserRoles.Location = new System.Drawing.Point(621, 64);
            this.TextBoxUserRoles.Name = "TextBoxUserRoles";
            this.TextBoxUserRoles.ReadOnly = true;
            this.TextBoxUserRoles.Size = new System.Drawing.Size(350, 23);
            this.TextBoxUserRoles.TabIndex = 7;
            // 
            // ultraLabel4
            // 
            appearance5.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance5.TextHAlignAsString = "Right";
            this.ultraLabel4.Appearance = appearance5;
            this.ultraLabel4.AutoSize = true;
            this.ultraLabel4.Location = new System.Drawing.Point(556, 68);
            this.ultraLabel4.Name = "ultraLabel4";
            this.ultraLabel4.Size = new System.Drawing.Size(59, 16);
            this.ultraLabel4.TabIndex = 6;
            this.ultraLabel4.Text = "User roles";
            // 
            // TextBoxUserName
            // 
            this.TextBoxUserName.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxUserName.Location = new System.Drawing.Point(77, 64);
            this.TextBoxUserName.Name = "TextBoxUserName";
            this.TextBoxUserName.ReadOnly = true;
            this.TextBoxUserName.Size = new System.Drawing.Size(350, 23);
            this.TextBoxUserName.TabIndex = 5;
            // 
            // ultraLabel3
            // 
            appearance4.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance4.TextHAlignAsString = "Right";
            this.ultraLabel3.Appearance = appearance4;
            this.ultraLabel3.AutoSize = true;
            this.ultraLabel3.Location = new System.Drawing.Point(28, 68);
            this.ultraLabel3.Name = "ultraLabel3";
            this.ultraLabel3.Size = new System.Drawing.Size(46, 16);
            this.ultraLabel3.TabIndex = 4;
            this.ultraLabel3.Text = "User ID";
            // 
            // TextBoxSeverity
            // 
            this.TextBoxSeverity.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxSeverity.Location = new System.Drawing.Point(621, 31);
            this.TextBoxSeverity.Name = "TextBoxSeverity";
            this.TextBoxSeverity.ReadOnly = true;
            this.TextBoxSeverity.Size = new System.Drawing.Size(350, 23);
            this.TextBoxSeverity.TabIndex = 3;
            // 
            // ultraLabel2
            // 
            appearance3.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance3.TextHAlignAsString = "Right";
            this.ultraLabel2.Appearance = appearance3;
            this.ultraLabel2.AutoSize = true;
            this.ultraLabel2.Location = new System.Drawing.Point(567, 35);
            this.ultraLabel2.Name = "ultraLabel2";
            this.ultraLabel2.Size = new System.Drawing.Size(48, 16);
            this.ultraLabel2.TabIndex = 2;
            this.ultraLabel2.Text = "Severity";
            // 
            // TextBoxTime
            // 
            this.TextBoxTime.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxTime.Location = new System.Drawing.Point(77, 31);
            this.TextBoxTime.Name = "TextBoxTime";
            this.TextBoxTime.ReadOnly = true;
            this.TextBoxTime.Size = new System.Drawing.Size(350, 23);
            this.TextBoxTime.TabIndex = 1;
            // 
            // ultraLabel1
            // 
            appearance2.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance2.TextHAlignAsString = "Right";
            this.ultraLabel1.Appearance = appearance2;
            this.ultraLabel1.AutoSize = true;
            this.ultraLabel1.Location = new System.Drawing.Point(43, 35);
            this.ultraLabel1.Name = "ultraLabel1";
            this.ultraLabel1.Size = new System.Drawing.Size(31, 16);
            this.ultraLabel1.TabIndex = 0;
            this.ultraLabel1.Text = "Time";
            // 
            // ExceptionLogDetailView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            this.AutoScrollMinSize = new System.Drawing.Size(978, 313);
            this.CancelButton = this.ButtonClose;
            this.Controls.Add(this.ultraGroupBox1);
            this.Name = "ExceptionLogDetailView";
            this.Size = new System.Drawing.Size(978, 513);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox1)).EndInit();
            this.ultraGroupBox1.ResumeLayout(false);
            this.ultraGroupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxPCName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxIPAddress)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxComponent)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxOffice)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxUserRoles)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxUserName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxSeverity)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxTime)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox1;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxTime;
        private Infragistics.Win.Misc.UltraLabel ultraLabel1;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxSeverity;
        private Infragistics.Win.Misc.UltraLabel ultraLabel2;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxUserName;
        private Infragistics.Win.Misc.UltraLabel ultraLabel3;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxUserRoles;
        private Infragistics.Win.Misc.UltraLabel ultraLabel4;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxOffice;
        private Infragistics.Win.Misc.UltraLabel ultraLabel5;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxPCName;
        private Infragistics.Win.Misc.UltraLabel ultraLabel8;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxIPAddress;
        private Infragistics.Win.Misc.UltraLabel ultraLabel7;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxComponent;
        private Infragistics.Win.Misc.UltraLabel ultraLabel6;
        private Infragistics.Win.Misc.UltraLabel ultraLabel9;
        private Infragistics.Win.Misc.UltraButton ButtonClose;
        private Infragistics.Win.FormattedLinkLabel.UltraFormattedTextEditor TextBoxContent;


    }
}

