
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace HiiP.Framework.Logging
{
    partial class InstrumentationDetailView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private HiiP.Framework.Logging.InstrumentationDetailViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            this.ultraGroupBox1 = new Infragistics.Win.Misc.UltraGroupBox();
            this.TextBoxParameterValues = new Infragistics.Win.FormattedLinkLabel.UltraFormattedTextEditor();
            this.ButtonClose = new Infragistics.Win.Misc.UltraButton();
            this.ultraLabel9 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxFunctionID = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.TextBoxEndTicks = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.TextBoxPCName = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel13 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel11 = new Infragistics.Win.Misc.UltraLabel();
            this.ultraLabel8 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxModuleID = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel12 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxDuration = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel2 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxStartTicks = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel10 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxMethodName = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel14 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxIPAddress = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel7 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxComponent = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel6 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxOffice = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel5 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxUserRoles = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel4 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxUserName = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel3 = new Infragistics.Win.Misc.UltraLabel();
            this.TextBoxTime = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel1 = new Infragistics.Win.Misc.UltraLabel();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox1)).BeginInit();
            this.ultraGroupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxFunctionID)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxEndTicks)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxPCName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxModuleID)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxDuration)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxStartTicks)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxMethodName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxIPAddress)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxComponent)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxOffice)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxUserRoles)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxUserName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxTime)).BeginInit();
            this.SuspendLayout();
            // 
            // ultraGroupBox1
            // 
            this.ultraGroupBox1.Controls.Add(this.TextBoxParameterValues);
            this.ultraGroupBox1.Controls.Add(this.ButtonClose);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel9);
            this.ultraGroupBox1.Controls.Add(this.TextBoxFunctionID);
            this.ultraGroupBox1.Controls.Add(this.TextBoxEndTicks);
            this.ultraGroupBox1.Controls.Add(this.TextBoxPCName);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel13);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel11);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel8);
            this.ultraGroupBox1.Controls.Add(this.TextBoxModuleID);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel12);
            this.ultraGroupBox1.Controls.Add(this.TextBoxDuration);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel2);
            this.ultraGroupBox1.Controls.Add(this.TextBoxStartTicks);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel10);
            this.ultraGroupBox1.Controls.Add(this.TextBoxMethodName);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel14);
            this.ultraGroupBox1.Controls.Add(this.TextBoxIPAddress);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel7);
            this.ultraGroupBox1.Controls.Add(this.TextBoxComponent);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel6);
            this.ultraGroupBox1.Controls.Add(this.TextBoxOffice);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel5);
            this.ultraGroupBox1.Controls.Add(this.TextBoxUserRoles);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel4);
            this.ultraGroupBox1.Controls.Add(this.TextBoxUserName);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel3);
            this.ultraGroupBox1.Controls.Add(this.TextBoxTime);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel1);
            this.ultraGroupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox1.Location = new System.Drawing.Point(0, 0);
            this.ultraGroupBox1.Name = "ultraGroupBox1";
            this.ultraGroupBox1.Size = new System.Drawing.Size(978, 513);
            this.ultraGroupBox1.TabIndex = 0;
            this.ultraGroupBox1.Text = "Instrumentation log details";
            this.ultraGroupBox1.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
            // 
            // TextBoxParameterValues
            // 
            this.TextBoxParameterValues.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.TextBoxParameterValues.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxParameterValues.Location = new System.Drawing.Point(115, 241);
            this.TextBoxParameterValues.Name = "TextBoxParameterValues";
            this.TextBoxParameterValues.ReadOnly = true;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2007;
            this.TextBoxParameterValues.ScrollBarLook = scrollBarLook1;
            this.TextBoxParameterValues.Size = new System.Drawing.Size(856, 236);
            this.TextBoxParameterValues.TabIndex = 27;
            this.TextBoxParameterValues.Value = "";
            // 
            // ButtonClose
            // 
            this.ButtonClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ButtonClose.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ButtonClose.Location = new System.Drawing.Point(884, 482);
            this.ButtonClose.Name = "ButtonClose";
            this.ButtonClose.Size = new System.Drawing.Size(87, 25);
            this.ButtonClose.TabIndex = 28;
            this.ButtonClose.Text = "&Close";
            this.ButtonClose.Click += new System.EventHandler(this.ButtonClose_Click);
            // 
            // ultraLabel9
            // 
            appearance1.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance1.TextHAlignAsString = "Right";
            this.ultraLabel9.Appearance = appearance1;
            this.ultraLabel9.Location = new System.Drawing.Point(8, 245);
            this.ultraLabel9.Name = "ultraLabel9";
            this.ultraLabel9.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel9.TabIndex = 26;
            this.ultraLabel9.Text = "Parameter values";
            // 
            // TextBoxFunctionID
            // 
            this.TextBoxFunctionID.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxFunctionID.Location = new System.Drawing.Point(115, 151);
            this.TextBoxFunctionID.Name = "TextBoxFunctionID";
            this.TextBoxFunctionID.ReadOnly = true;
            this.TextBoxFunctionID.Size = new System.Drawing.Size(350, 23);
            this.TextBoxFunctionID.TabIndex = 17;
            // 
            // TextBoxEndTicks
            // 
            this.TextBoxEndTicks.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxEndTicks.Location = new System.Drawing.Point(621, 91);
            this.TextBoxEndTicks.Name = "TextBoxEndTicks";
            this.TextBoxEndTicks.ReadOnly = true;
            this.TextBoxEndTicks.Size = new System.Drawing.Size(350, 23);
            this.TextBoxEndTicks.TabIndex = 11;
            // 
            // TextBoxPCName
            // 
            this.TextBoxPCName.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxPCName.Location = new System.Drawing.Point(621, 181);
            this.TextBoxPCName.Name = "TextBoxPCName";
            this.TextBoxPCName.ReadOnly = true;
            this.TextBoxPCName.Size = new System.Drawing.Size(350, 23);
            this.TextBoxPCName.TabIndex = 23;
            // 
            // ultraLabel13
            // 
            appearance9.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance9.TextHAlignAsString = "Right";
            this.ultraLabel13.Appearance = appearance9;
            this.ultraLabel13.Location = new System.Drawing.Point(10, 155);
            this.ultraLabel13.Name = "ultraLabel13";
            this.ultraLabel13.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel13.TabIndex = 16;
            this.ultraLabel13.Text = "Function ID";
            // 
            // ultraLabel11
            // 
            appearance3.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance3.TextHAlignAsString = "Right";
            this.ultraLabel11.Appearance = appearance3;
            this.ultraLabel11.Location = new System.Drawing.Point(517, 95);
            this.ultraLabel11.Name = "ultraLabel11";
            this.ultraLabel11.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel11.TabIndex = 10;
            this.ultraLabel11.Text = "End ticks";
            // 
            // ultraLabel8
            // 
            appearance11.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance11.TextHAlignAsString = "Right";
            this.ultraLabel8.Appearance = appearance11;
            this.ultraLabel8.Location = new System.Drawing.Point(517, 185);
            this.ultraLabel8.Name = "ultraLabel8";
            this.ultraLabel8.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel8.TabIndex = 22;
            this.ultraLabel8.Text = "Machine name";
            // 
            // TextBoxModuleID
            // 
            this.TextBoxModuleID.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxModuleID.Location = new System.Drawing.Point(621, 121);
            this.TextBoxModuleID.Name = "TextBoxModuleID";
            this.TextBoxModuleID.ReadOnly = true;
            this.TextBoxModuleID.Size = new System.Drawing.Size(350, 23);
            this.TextBoxModuleID.TabIndex = 15;
            // 
            // ultraLabel12
            // 
            appearance6.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance6.TextHAlignAsString = "Right";
            this.ultraLabel12.Appearance = appearance6;
            this.ultraLabel12.Location = new System.Drawing.Point(515, 125);
            this.ultraLabel12.Name = "ultraLabel12";
            this.ultraLabel12.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel12.TabIndex = 14;
            this.ultraLabel12.Text = "Module ID";
            // 
            // TextBoxDuration
            // 
            this.TextBoxDuration.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxDuration.Location = new System.Drawing.Point(115, 121);
            this.TextBoxDuration.Name = "TextBoxDuration";
            this.TextBoxDuration.ReadOnly = true;
            this.TextBoxDuration.Size = new System.Drawing.Size(350, 23);
            this.TextBoxDuration.TabIndex = 13;
            // 
            // ultraLabel2
            // 
            appearance12.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance12.TextHAlignAsString = "Right";
            this.ultraLabel2.Appearance = appearance12;
            this.ultraLabel2.Location = new System.Drawing.Point(8, 125);
            this.ultraLabel2.Name = "ultraLabel2";
            this.ultraLabel2.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel2.TabIndex = 12;
            this.ultraLabel2.Text = "Duration";
            // 
            // TextBoxStartTicks
            // 
            this.TextBoxStartTicks.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxStartTicks.Location = new System.Drawing.Point(115, 91);
            this.TextBoxStartTicks.Name = "TextBoxStartTicks";
            this.TextBoxStartTicks.ReadOnly = true;
            this.TextBoxStartTicks.Size = new System.Drawing.Size(350, 23);
            this.TextBoxStartTicks.TabIndex = 9;
            // 
            // ultraLabel10
            // 
            appearance14.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance14.TextHAlignAsString = "Right";
            this.ultraLabel10.Appearance = appearance14;
            this.ultraLabel10.Location = new System.Drawing.Point(8, 95);
            this.ultraLabel10.Name = "ultraLabel10";
            this.ultraLabel10.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel10.TabIndex = 8;
            this.ultraLabel10.Text = "Start ticks";
            // 
            // TextBoxMethodName
            // 
            this.TextBoxMethodName.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxMethodName.Location = new System.Drawing.Point(115, 211);
            this.TextBoxMethodName.Name = "TextBoxMethodName";
            this.TextBoxMethodName.ReadOnly = true;
            this.TextBoxMethodName.Size = new System.Drawing.Size(350, 23);
            this.TextBoxMethodName.TabIndex = 25;
            // 
            // ultraLabel14
            // 
            appearance13.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance13.TextHAlignAsString = "Right";
            this.ultraLabel14.Appearance = appearance13;
            this.ultraLabel14.Location = new System.Drawing.Point(8, 215);
            this.ultraLabel14.Name = "ultraLabel14";
            this.ultraLabel14.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel14.TabIndex = 24;
            this.ultraLabel14.Text = "Method name";
            // 
            // TextBoxIPAddress
            // 
            this.TextBoxIPAddress.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxIPAddress.Location = new System.Drawing.Point(115, 181);
            this.TextBoxIPAddress.Name = "TextBoxIPAddress";
            this.TextBoxIPAddress.ReadOnly = true;
            this.TextBoxIPAddress.Size = new System.Drawing.Size(350, 23);
            this.TextBoxIPAddress.TabIndex = 21;
            // 
            // ultraLabel7
            // 
            appearance15.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance15.TextHAlignAsString = "Right";
            this.ultraLabel7.Appearance = appearance15;
            this.ultraLabel7.Location = new System.Drawing.Point(8, 185);
            this.ultraLabel7.Name = "ultraLabel7";
            this.ultraLabel7.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel7.TabIndex = 20;
            this.ultraLabel7.Text = "IP address";
            // 
            // TextBoxComponent
            // 
            this.TextBoxComponent.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxComponent.Location = new System.Drawing.Point(621, 151);
            this.TextBoxComponent.Name = "TextBoxComponent";
            this.TextBoxComponent.ReadOnly = true;
            this.TextBoxComponent.Size = new System.Drawing.Size(350, 23);
            this.TextBoxComponent.TabIndex = 19;
            // 
            // ultraLabel6
            // 
            appearance7.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance7.TextHAlignAsString = "Right";
            this.ultraLabel6.Appearance = appearance7;
            this.ultraLabel6.Location = new System.Drawing.Point(517, 155);
            this.ultraLabel6.Name = "ultraLabel6";
            this.ultraLabel6.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel6.TabIndex = 18;
            this.ultraLabel6.Text = "Component";
            // 
            // TextBoxOffice
            // 
            this.TextBoxOffice.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxOffice.Location = new System.Drawing.Point(621, 61);
            this.TextBoxOffice.Name = "TextBoxOffice";
            this.TextBoxOffice.ReadOnly = true;
            this.TextBoxOffice.Size = new System.Drawing.Size(350, 23);
            this.TextBoxOffice.TabIndex = 7;
            // 
            // ultraLabel5
            // 
            appearance8.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance8.TextHAlignAsString = "Right";
            this.ultraLabel5.Appearance = appearance8;
            this.ultraLabel5.Location = new System.Drawing.Point(515, 65);
            this.ultraLabel5.Name = "ultraLabel5";
            this.ultraLabel5.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel5.TabIndex = 6;
            this.ultraLabel5.Text = "Office";
            // 
            // TextBoxUserRoles
            // 
            this.TextBoxUserRoles.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxUserRoles.Location = new System.Drawing.Point(115, 61);
            this.TextBoxUserRoles.Name = "TextBoxUserRoles";
            this.TextBoxUserRoles.ReadOnly = true;
            this.TextBoxUserRoles.Size = new System.Drawing.Size(350, 23);
            this.TextBoxUserRoles.TabIndex = 5;
            // 
            // ultraLabel4
            // 
            appearance5.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance5.TextHAlignAsString = "Right";
            this.ultraLabel4.Appearance = appearance5;
            this.ultraLabel4.Location = new System.Drawing.Point(10, 65);
            this.ultraLabel4.Name = "ultraLabel4";
            this.ultraLabel4.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel4.TabIndex = 4;
            this.ultraLabel4.Text = "User roles";
            // 
            // TextBoxUserName
            // 
            this.TextBoxUserName.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxUserName.Location = new System.Drawing.Point(621, 31);
            this.TextBoxUserName.Name = "TextBoxUserName";
            this.TextBoxUserName.ReadOnly = true;
            this.TextBoxUserName.Size = new System.Drawing.Size(350, 23);
            this.TextBoxUserName.TabIndex = 3;
            // 
            // ultraLabel3
            // 
            appearance4.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance4.TextHAlignAsString = "Right";
            this.ultraLabel3.Appearance = appearance4;
            this.ultraLabel3.Location = new System.Drawing.Point(517, 35);
            this.ultraLabel3.Name = "ultraLabel3";
            this.ultraLabel3.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel3.TabIndex = 2;
            this.ultraLabel3.Text = "User ID";
            // 
            // TextBoxTime
            // 
            this.TextBoxTime.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.TextBoxTime.Location = new System.Drawing.Point(115, 31);
            this.TextBoxTime.Name = "TextBoxTime";
            this.TextBoxTime.ReadOnly = true;
            this.TextBoxTime.Size = new System.Drawing.Size(350, 23);
            this.TextBoxTime.TabIndex = 1;
            // 
            // ultraLabel1
            // 
            appearance2.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance2.TextHAlignAsString = "Right";
            this.ultraLabel1.Appearance = appearance2;
            this.ultraLabel1.Location = new System.Drawing.Point(8, 35);
            this.ultraLabel1.Name = "ultraLabel1";
            this.ultraLabel1.Size = new System.Drawing.Size(99, 25);
            this.ultraLabel1.TabIndex = 0;
            this.ultraLabel1.Text = "Time";
            // 
            // InstrumentationDetailView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            this.AutoScrollMinSize = new System.Drawing.Size(978, 313);
            this.CancelButton = this.ButtonClose;
            this.Controls.Add(this.ultraGroupBox1);
            this.Name = "InstrumentationDetailView";
            this.Size = new System.Drawing.Size(978, 513);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox1)).EndInit();
            this.ultraGroupBox1.ResumeLayout(false);
            this.ultraGroupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxFunctionID)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxEndTicks)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxPCName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxModuleID)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxDuration)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxStartTicks)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxMethodName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxIPAddress)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxComponent)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxOffice)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxUserRoles)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxUserName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TextBoxTime)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox1;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxTime;
        private Infragistics.Win.Misc.UltraLabel ultraLabel1;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxUserName;
        private Infragistics.Win.Misc.UltraLabel ultraLabel3;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxUserRoles;
        private Infragistics.Win.Misc.UltraLabel ultraLabel4;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxOffice;
        private Infragistics.Win.Misc.UltraLabel ultraLabel5;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxPCName;
        private Infragistics.Win.Misc.UltraLabel ultraLabel8;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxIPAddress;
        private Infragistics.Win.Misc.UltraLabel ultraLabel7;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxComponent;
        private Infragistics.Win.Misc.UltraLabel ultraLabel6;
        private Infragistics.Win.Misc.UltraLabel ultraLabel9;
        private Infragistics.Win.Misc.UltraButton ButtonClose;
        private Infragistics.Win.FormattedLinkLabel.UltraFormattedTextEditor TextBoxParameterValues;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxFunctionID;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxEndTicks;
        private Infragistics.Win.Misc.UltraLabel ultraLabel13;
        private Infragistics.Win.Misc.UltraLabel ultraLabel11;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxModuleID;
        private Infragistics.Win.Misc.UltraLabel ultraLabel12;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxStartTicks;
        private Infragistics.Win.Misc.UltraLabel ultraLabel10;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxDuration;
        private Infragistics.Win.Misc.UltraLabel ultraLabel2;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor TextBoxMethodName;
        private Infragistics.Win.Misc.UltraLabel ultraLabel14;


    }
}

