using System.Reflection;
using System.Runtime.InteropServices;
using System.Diagnostics.CodeAnalysis;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Settings")]
[assembly: AssemblyDescription("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("bdb5c1ee-832d-4983-a3b4-547e31603385")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Revision and Build Numbers 
// by using the '*' as shown below:
[assembly: AssemblyFileVersion("1.0.0.0")]


[module: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "HiiP.Framework.Settings.IInstrumentationFilterView")]
[module: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "HiiP.Framework.Settings.IBinaryFormatterView")]
[module: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "HiiP.Framework.Settings.IBatchJobServiceConfiguration")]
[module: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "HiiP.Framework.Settings.ITextFormatterView")]
[module: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "HiiP.Framework.Settings.IMsmqTraceListenerView")]
[module: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "HiiP.Framework.Settings.ILogEnabledFilterView")]
[module: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "HiiP.Framework.Settings.IEmailTraceListenerView")]
[module: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "HiiP.Framework.Settings.IFormattedEventLogTraceListenerView")]
[module: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "HiiP.Framework.Settings.IMonitoringDatabaseTraceListenerView")]
[module: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "HiiP.Framework.Settings.ServiceProxy")]
[module: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "HiiP.Framework.Settings.Constants")]
[module: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "HiiP.Settings.Constants")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "type", Target = "HiiP.Framework.Settings.IHomePageRefreshConfiguration", MessageId = "HomePage")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "type", Target = "HiiP.Framework.Settings.HomePageRefreshConfigurationPresenter", MessageId = "HomePage")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "type", Target = "HiiP.Framework.Settings.HomePageRefreshConfiguration", MessageId = "HomePage")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowHomePageRefreshSettingsView(System.Object,System.EventArgs)", MessageId = "HomePage")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowHomePageRefreshSettingsMenu(System.Object,System.Object)", MessageId = "HomePage")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableDetailView.#BindCategory(System.Collections.Generic.List`1<System.String>)")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "HiiP.Framework.Settings.MessageDetailView.#BindCategory(System.Collections.Generic.List`1<System.String>)")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "HiiP.Framework.Settings.ICodeTableMaintain.#BindCategory(System.Collections.Generic.List`1<System.String>)")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "HiiP.Framework.Settings.IMessageDetailView.#BindCategory(System.Collections.Generic.List`1<System.String>)")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableMaintainPresenter.#GetBindingCategories()")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableMaintain.#BindCategory(System.Collections.Generic.List`1<System.String>)")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "HiiP.Framework.Settings.ICodeTableDetailView.#BindCategory(System.Collections.Generic.List`1<System.String>)")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Settings.LoggingFilterMaintain.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Settings.InstrumentationFilterView.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableDetailView.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Settings.MessageDetailView.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Settings.LoggingConfiguration.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Settings.ExceptionHandlingConfiguration.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Settings.BatchJobServiceConfiguration.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Settings.MessageMaintain.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Settings.HomePageRefreshConfiguration.#.ctor()")]
[module: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableMaintain.#.ctor()")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "HiiP.Framework.Settings.IExceptionHandlingConfiguration.#EventID", MessageId = "ID")]
[module: SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", Scope = "type", Target = "HiiP.Framework.Settings.Module", MessageId = "Module")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "HiiP.Framework.Settings.InstrumentationFilterViewPresenter.#GetAllUsers()")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "HiiP.Framework.Settings.InstrumentationFilterViewPresenter.#IsUserExists(System.String,System.String)")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "HiiP.Framework.Settings.HomePageRefreshConfigurationPresenter.#GetData(NCS.IConnect.Hierarchy.Parameter.ParameterManager,System.String)")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "HiiP.Framework.Settings.HomePageRefreshConfigurationPresenter.#SaveParameterKey(System.String,System.String)")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "HiiP.Framework.Settings.LoggingFilterMaintainPresenter.#GetLoggingFilterByCategory(System.String)")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "HiiP.Framework.Settings.MessageMaintainPresenter.#GetSeverity()")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "HiiP.Framework.Settings.MessageMaintainPresenter.#GenerateMessageTable()")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "HiiP.Framework.Settings.ExceptionHandlingConfigurationPresenter.#GetLoggingSettings()")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "HiiP.Framework.Settings.ExceptionHandlingConfigurationPresenter.#GetExceptionSettings()")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableMaintainPresenter.#Update(NCS.IConnect.CodeTable.CodeTableDataSet+T_IC_CODEDataTable)")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "HiiP.Framework.Settings.LoggingConfigurationPresenter.#GetLoggingSettings()")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowLoggingSettingsMenu(System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "HiiP.Framework.Settings.MessageDetailViewPresenter.#GetSeverity()")]
[module: SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableDetailView.#ultraButtonSave_Click(System.Object,System.EventArgs)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableDetailViewPresenter.#CreateEmptyRow()")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.LoggingFilterMaintain.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.InstrumentationFilterView.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableDetailView.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.BinaryFormatterView.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.MonitoringDatabaseTraceListenerView.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.MessageDetailView.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.LoggingConfiguration.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.ExceptionHandlingConfiguration.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.MsmqTraceListenerView.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.BatchJobServiceConfiguration.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.TextFormatterView.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.MessageMaintain.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.FormattedEventLogTraceListenerView.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.HomePageRefreshConfiguration.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableMaintain.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.LogEnabledFilterView.#Presenter")]
[module: SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "HiiP.Framework.Settings.EmailTraceListenerView.#Presenter")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowLoggingSettingsMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowLoggingSettingsMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowSettingsMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowSettingsMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowMessageMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowMessageMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowCodeTableMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowCodeTableMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowBatchJobServiceSettingsMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowBatchJobServiceSettingsMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowLoggingFilterMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowLoggingFilterMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowExceptionHandlingSettingsMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowExceptionHandlingSettingsMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowHomePageRefreshSettingsMenu(System.Object,System.Object)", MessageId = "target")]
[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowHomePageRefreshSettingsMenu(System.Object,System.Object)", MessageId = "caller")]
[module: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "HiiP.Framework.Settings.LoggingFilterMaintain.#OnAddInstrumentationFilter(System.Object,System.EventArgs)")]
[module: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "HiiP.Framework.Settings.MessageMaintainPresenter.#OnMessageSaveEvent(System.Object,HiiP.Framework.Settings.BusinessEntity.KeyValueEventArgs)")]
[module: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableMaintainPresenter.#OnClosedDetail(System.Object,HiiP.Framework.Settings.BusinessEntity.KeyValueEventArgs)")]
[module: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowLoggingSettingsView(System.Object,System.EventArgs)")]
[module: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowMessageView(System.Object,System.EventArgs)")]
[module: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowBatchJobServiceSettingsView(System.Object,System.EventArgs)")]
[module: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowExceptionSettingsView(System.Object,System.EventArgs)")]
[module: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowMessageDetail(System.Object,System.EventArgs)")]
[module: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowCodeTableView(System.Object,System.EventArgs)")]
[module: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowHomePageRefreshSettingsView(System.Object,System.EventArgs)")]
[module: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "HiiP.Framework.Settings.ModuleController.#ShowLoggingFilterView(System.Object,System.EventArgs)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1306:SetLocaleForDataTypes", Scope = "member", Target = "HiiP.Framework.Settings.MessageMaintainPresenter.#GenerateMessageTable()")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "HiiP.Framework.Settings.LoggingFilterMaintain.#BindGrid(HiiP.Framework.Settings.BusinessEntity.LoggingFilterDS)", MessageId = "System.Int32.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "HiiP.Framework.Settings.InstrumentationFilterView.#validationProvider1_ValueConvert(System.Object,Microsoft.Practices.EnterpriseLibrary.Validation.Integration.ValueConvertEventArgs)", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "HiiP.Framework.Settings.HomePageRefreshConfigurationPresenter.#SaveParameterKey(System.String,System.String)", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "HiiP.Framework.Settings.ExceptionHandlingConfiguration.#get_Priority()", MessageId = "System.Convert.ToInt32(System.String)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "HiiP.Framework.Settings.ExceptionHandlingConfiguration.#SetLoggingExceptionHandler(HiiP.Framework.Logging.Library.HiiPLoggingExceptionHandlerData)", MessageId = "System.Int32.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "HiiP.Framework.Settings.ExceptionHandlingConfiguration.#get_EventID()", MessageId = "System.Convert.ToInt32(System.String)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "HiiP.Framework.Settings.MessageMaintainPresenter.#UpdateMessage(Infragistics.Win.UltraWinGrid.UltraGridRow)", MessageId = "System.String.Format(System.String,System.Object,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableMaintainPresenter.#DisplayDetail(System.String,System.String,System.String)", MessageId = "System.String.Format(System.String,System.Object,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableMaintainPresenter.#DisplayDetail(System.String,System.String,System.String)", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableMaintainPresenter.#DisplayDetail(System.String,System.String,System.String)", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1300:SpecifyMessageBoxOptions", Scope = "member", Target = "HiiP.Framework.Settings.LoggingFilterMaintain.#ButtonDelete_Click(System.Object,System.EventArgs)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1309:UseOrdinalStringComparison", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableDetailView.#validationProvider_ValueConvert(System.Object,Microsoft.Practices.EnterpriseLibrary.Validation.Integration.ValueConvertEventArgs)", MessageId = "System.String.Equals(System.String,System.StringComparison)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1309:UseOrdinalStringComparison", Scope = "member", Target = "HiiP.Framework.Settings.MessageDetailView.#OnClosingExtension()", MessageId = "System.String.Equals(System.String,System.StringComparison)")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "HiiP.Framework.Settings.IExceptionHandlingConfiguration.#SetLoggingEnable(System.Boolean)", MessageId = "flag")]
[module: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "HiiP.Framework.Settings.ILoggingConfiguration.#GetSelectedSpecialSourceName()")]
[module: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "HiiP.Framework.Settings.ILoggingConfiguration.#GetSelectedFilterName()")]
[module: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "HiiP.Framework.Settings.ILoggingConfiguration.#GetSelectedListenerName()")]
[module: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "HiiP.Framework.Settings.ILoggingConfiguration.#GetSelectedSourceName()")]
[module: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "HiiP.Framework.Settings.ILoggingConfiguration.#GetSelectedFormatterName()")]
[module: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "HiiP.Framework.Settings.CodeTableMaintainPresenter.#GetBindingCategories()")]

[module: SuppressMessage("HiiP.Usages", "HP1005:AcceptCancelButtonNonexistence", Scope = "type", Target = "HiiP.Framework.Settings.LoggingFilterMaintain", MessageId = "AcceptButtonNonexistence")]
