
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace HiiP.Framework.Security.UserManagement
{
    partial class RoleDetail
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private RoleDetailPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            this.ultraGroupBox2 = new Infragistics.Win.Misc.UltraGroupBox();
            this.tv_systemadmin = new System.Windows.Forms.TreeView();
            this.btn_ok = new Infragistics.Win.Misc.UltraButton();
            this.btn_cancel = new Infragistics.Win.Misc.UltraButton();
            this.ultraGroupBox1 = new Infragistics.Win.Misc.UltraGroupBox();
            this.ultraLabel12 = new Infragistics.Win.Misc.UltraLabel();
            this.txt_description = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel11 = new Infragistics.Win.Misc.UltraLabel();
            this.txt_rolename = new HiiP.Framework.Common.Client.ExtendedUltraTextEditor();
            this.ultraLabel46 = new Infragistics.Win.Misc.UltraLabel();
            this.btn_delete = new Infragistics.Win.Misc.UltraButton();
            this.validationProvider = new Microsoft.Practices.EnterpriseLibrary.Validation.Integration.WinForms.ValidationProvider();
            this.errorProvider = new System.Windows.Forms.ErrorProvider(this.components);
            this.CopyButton = new Infragistics.Win.Misc.UltraButton();
            this.RoleFlowLayoutPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.btn_viewusers = new Infragistics.Win.Misc.UltraButton();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox2)).BeginInit();
            this.ultraGroupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox1)).BeginInit();
            this.ultraGroupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.txt_description)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt_rolename)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider)).BeginInit();
            this.RoleFlowLayoutPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // ultraGroupBox2
            // 
            this.ultraGroupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.ultraGroupBox2.Controls.Add(this.tv_systemadmin);
            this.ultraGroupBox2.Location = new System.Drawing.Point(7, 163);
            this.ultraGroupBox2.Name = "ultraGroupBox2";
            this.ultraGroupBox2.Size = new System.Drawing.Size(1196, 646);
            this.ultraGroupBox2.TabIndex = 1;
            this.ultraGroupBox2.Text = " Functions";
            this.ultraGroupBox2.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
            // 
            // tv_systemadmin
            // 
            this.tv_systemadmin.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.tv_systemadmin.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tv_systemadmin.CheckBoxes = true;
            this.tv_systemadmin.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tv_systemadmin.Location = new System.Drawing.Point(12, 28);
            this.tv_systemadmin.Name = "tv_systemadmin";
            this.tv_systemadmin.Size = new System.Drawing.Size(1168, 604);
            this.tv_systemadmin.TabIndex = 0;
            this.tv_systemadmin.AfterCheck += new System.Windows.Forms.TreeViewEventHandler(this.tv_systemadmin_AfterCheck);
            this.tv_systemadmin.BeforeCheck += new System.Windows.Forms.TreeViewCancelEventHandler(this.tv_systemadmin_BeforeCheck);
            // 
            // btn_ok
            // 
            this.btn_ok.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_ok.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.btn_ok.Location = new System.Drawing.Point(3, 3);
            this.btn_ok.Name = "btn_ok";
            this.btn_ok.Size = new System.Drawing.Size(87, 25);
            this.btn_ok.TabIndex = 0;
            this.btn_ok.Text = "&Save";
            this.btn_ok.Click += new System.EventHandler(this.btn_ok_Click);
            // 
            // btn_cancel
            // 
            this.btn_cancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_cancel.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.btn_cancel.Location = new System.Drawing.Point(375, 3);
            this.btn_cancel.Name = "btn_cancel";
            this.btn_cancel.Size = new System.Drawing.Size(87, 25);
            this.btn_cancel.TabIndex = 4;
            this.btn_cancel.Text = "&Cancel";
            this.btn_cancel.Click += new System.EventHandler(this.btn_cancel_Click);
            // 
            // ultraGroupBox1
            // 
            this.ultraGroupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.ultraGroupBox1.Controls.Add(this.ultraLabel12);
            this.ultraGroupBox1.Controls.Add(this.txt_description);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel11);
            this.ultraGroupBox1.Controls.Add(this.txt_rolename);
            this.ultraGroupBox1.Controls.Add(this.ultraLabel46);
            this.ultraGroupBox1.Location = new System.Drawing.Point(5, 6);
            this.ultraGroupBox1.Name = "ultraGroupBox1";
            this.ultraGroupBox1.Size = new System.Drawing.Size(1198, 152);
            this.ultraGroupBox1.TabIndex = 0;
            this.ultraGroupBox1.Text = "Role details";
            this.ultraGroupBox1.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
            // 
            // ultraLabel12
            // 
            appearance1.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance1.TextHAlignAsString = "Right";
            this.ultraLabel12.Appearance = appearance1;
            this.ultraLabel12.Location = new System.Drawing.Point(0, 89);
            this.ultraLabel12.Name = "ultraLabel12";
            this.ultraLabel12.Size = new System.Drawing.Size(154, 20);
            this.ultraLabel12.TabIndex = 4;
            this.ultraLabel12.Text = "(max 250 characters)";
            // 
            // txt_description
            // 
            this.txt_description.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.txt_description.Location = new System.Drawing.Point(163, 66);
            this.txt_description.Multiline = true;
            this.txt_description.AcceptsReturn = true;
            this.txt_description.Name = "txt_description";
            this.validationProvider.SetPerformValidation(this.txt_description, true);
            this.txt_description.Scrollbars = System.Windows.Forms.ScrollBars.Vertical;
            this.txt_description.Size = new System.Drawing.Size(372, 65);
            this.validationProvider.SetSourcePropertyName(this.txt_description, "Description");
            this.txt_description.TabIndex = 3;
            // 
            // ultraLabel11
            // 
            appearance3.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance3.TextHAlignAsString = "Right";
            this.ultraLabel11.Appearance = appearance3;
            this.ultraLabel11.Location = new System.Drawing.Point(0, 70);
            this.ultraLabel11.Name = "ultraLabel11";
            this.ultraLabel11.Size = new System.Drawing.Size(154, 20);
            this.ultraLabel11.TabIndex = 2;
            this.ultraLabel11.Text = "Description";
            // 
            // txt_rolename
            // 
            this.txt_rolename.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.txt_rolename.Location = new System.Drawing.Point(163, 37);
            this.txt_rolename.Name = "txt_rolename";
            this.validationProvider.SetPerformValidation(this.txt_rolename, true);
            this.txt_rolename.Size = new System.Drawing.Size(372, 23);
            this.validationProvider.SetSourcePropertyName(this.txt_rolename, "RoleName");
            this.txt_rolename.TabIndex = 1;
            // 
            // ultraLabel46
            // 
            appearance5.BackColorAlpha = Infragistics.Win.Alpha.Transparent;
            appearance5.TextHAlignAsString = "Right";
            this.ultraLabel46.Appearance = appearance5;
            this.ultraLabel46.Location = new System.Drawing.Point(24, 41);
            this.ultraLabel46.Name = "ultraLabel46";
            this.ultraLabel46.Size = new System.Drawing.Size(129, 25);
            this.ultraLabel46.TabIndex = 0;
            this.ultraLabel46.Text = "* Role name";
            // 
            // btn_delete
            // 
            this.btn_delete.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_delete.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.btn_delete.Location = new System.Drawing.Point(189, 3);
            this.btn_delete.Name = "btn_delete";
            this.btn_delete.Size = new System.Drawing.Size(87, 25);
            this.btn_delete.TabIndex = 2;
            this.btn_delete.Text = "&Delete";
            this.btn_delete.Click += new System.EventHandler(this.btn_delete_Click);
            // 
            // validationProvider
            // 
            this.validationProvider.ErrorProvider = this.errorProvider;
            this.validationProvider.RulesetName = "Role Operation Rule Set";
            this.validationProvider.SourceTypeName = "HiiP.Framework.Security.UserManagement.BusinessEntity.RoleEntity,HiiP.Framework.S" +
                "ecurity.UserManagement.BusinessEntity";
            this.validationProvider.ValueConvert += new System.EventHandler<Microsoft.Practices.EnterpriseLibrary.Validation.Integration.ValueConvertEventArgs>(this.validationProvider_ValueConvert);
            // 
            // errorProvider
            // 
            this.errorProvider.ContainerControl = this;
            // 
            // CopyButton
            // 
            this.CopyButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.CopyButton.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.CopyButton.Location = new System.Drawing.Point(282, 3);
            this.CopyButton.Name = "CopyButton";
            this.CopyButton.Size = new System.Drawing.Size(87, 25);
            this.CopyButton.TabIndex = 3;
            this.CopyButton.Text = "C&opy";
            this.CopyButton.Click += new System.EventHandler(this.CopyButton_Click);
            // 
            // RoleFlowLayoutPanel
            // 
            this.RoleFlowLayoutPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.RoleFlowLayoutPanel.AutoSize = true;
            this.RoleFlowLayoutPanel.Controls.Add(this.btn_cancel);
            this.RoleFlowLayoutPanel.Controls.Add(this.CopyButton);
            this.RoleFlowLayoutPanel.Controls.Add(this.btn_delete);
            this.RoleFlowLayoutPanel.Controls.Add(this.btn_viewusers);
            this.RoleFlowLayoutPanel.Controls.Add(this.btn_ok);
            this.RoleFlowLayoutPanel.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft;
            this.RoleFlowLayoutPanel.Location = new System.Drawing.Point(727, 815);
            this.RoleFlowLayoutPanel.Name = "RoleFlowLayoutPanel";
            this.RoleFlowLayoutPanel.Size = new System.Drawing.Size(465, 31);
            this.RoleFlowLayoutPanel.TabIndex = 2;
            // 
            // btn_viewusers
            // 
            this.btn_viewusers.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_viewusers.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.btn_viewusers.Location = new System.Drawing.Point(96, 3);
            this.btn_viewusers.Name = "btn_viewusers";
            this.btn_viewusers.Size = new System.Drawing.Size(87, 25);
            this.btn_viewusers.TabIndex = 1;
            this.btn_viewusers.Text = "&View users";
            this.btn_viewusers.Click += new System.EventHandler(this.btn_viewusers_Click);
            // 
            // RoleDetail
            // 
            this.AcceptButton = this.btn_ok;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            this.AutoSize = true;
            this.CancelButton = this.btn_cancel;
            this.CheckDirtyRequired = true;
            this.Controls.Add(this.RoleFlowLayoutPanel);
            this.Controls.Add(this.ultraGroupBox2);
            this.Controls.Add(this.ultraGroupBox1);
            this.Key = "AddRole";
            this.Name = "RoleDetail";
            this.Size = new System.Drawing.Size(1209, 852);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox2)).EndInit();
            this.ultraGroupBox2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox1)).EndInit();
            this.ultraGroupBox1.ResumeLayout(false);
            this.ultraGroupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.txt_description)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt_rolename)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider)).EndInit();
            this.RoleFlowLayoutPanel.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Infragistics.Win.Misc.UltraButton btn_ok;
        private Infragistics.Win.Misc.UltraButton btn_cancel;
        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox2;
        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox1;
        private Infragistics.Win.Misc.UltraLabel ultraLabel12;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor txt_description;
        private Infragistics.Win.Misc.UltraLabel ultraLabel11;
        private HiiP.Framework.Common.Client.ExtendedUltraTextEditor txt_rolename;
        private Infragistics.Win.Misc.UltraLabel ultraLabel46;
        private Infragistics.Win.Misc.UltraButton btn_delete;
        private Microsoft.Practices.EnterpriseLibrary.Validation.Integration.WinForms.ValidationProvider validationProvider;
        private System.Windows.Forms.ErrorProvider errorProvider;
        private System.Windows.Forms.TreeView tv_systemadmin;
        private System.Windows.Forms.FlowLayoutPanel RoleFlowLayoutPanel;
        private Infragistics.Win.Misc.UltraButton CopyButton;
        private Infragistics.Win.Misc.UltraButton btn_viewusers;
    }
}

